Repository citusdata/citus, pull requests merged in 2018-03, with the labels that each got.

#2008 Pushdown top level window functions
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/backend/distributed/planner/multi_logical_planner.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/include/distributed/multi_logical_planner.h
  src/test/regress/expected/multi_insert_select_window.out
  src/test/regress/expected/multi_mx_router_planner.out
  src/test/regress/expected/multi_router_planner.out
  src/test/regress/expected/multi_subquery_complex_queries.out
  src/test/regress/expected/multi_subquery_window_functions.out
  src/test/regress/expected/set_operations.out
  src/test/regress/expected/subqueries_not_supported.out
  src/test/regress/expected/window_functions.out
  src/test/regress/expected/with_basics.out
  src/test/regress/multi_schedule
  src/test/regress/sql/multi_subquery_complex_queries.sql
  src/test/regress/sql/window_functions.sql
Labels: needs review

#2031 Improve error handling on failures
  src/backend/distributed/connection/remote_commands.c
  src/backend/distributed/executor/multi_router_executor.c
  src/test/regress/expected/multi_extension.out
Labels: needs review

#2038 Improve error messages for INSERT queries that have subqueries
  src/backend/distributed/planner/multi_router_planner.c
  src/test/regress/expected/multi_modifications.out
  src/test/regress/expected/multi_upsert.out
  src/test/regress/sql/multi_modifications.sql
Labels: backport, needs review, priority:high

#2041 Change default to false for citus.skip_jsonb_validation_in_copy
  src/backend/distributed/shared_library_init.c
  src/test/regress/output/multi_copy.source
Labels: needs review

#2035 Fix incorrect limit pushdown when distinct clause is not superset of group by
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/backend/distributed/planner/multi_master_planner.c
  src/include/distributed/multi_logical_optimizer.h
  src/test/regress/expected/multi_limit_clause.out
  src/test/regress/expected/multi_select_distinct.out
  src/test/regress/sql/multi_limit_clause.sql
  src/test/regress/sql/multi_select_distinct.sql
Labels: needs review

#2056 Fixed a typo
  src/backend/distributed/transaction/distributed_deadlock_detection.c
Labels: CLA Signed
