Repository citusdata/citus, pull requests merged in 2018-04, with the labels that each got.

#2088 Prevent DROPping partitioned tables from workers
  src/backend/distributed/executor/multi_utility.c
  src/test/regress/expected/multi_mx_partitioning.out
  src/test/regress/expected/multi_mx_partitioning_0.out
  src/test/regress/sql/multi_mx_partitioning.sql
Labels: needs review

#2013 Prune shards once per relation in subquery pushdown
  src/backend/distributed/master/master_metadata_utility.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/utils/citus_copyfuncs.c
  src/backend/distributed/utils/citus_outfuncs.c
  src/backend/distributed/utils/citus_readfuncs.c
  src/backend/distributed/utils/metadata_cache.c
  src/include/distributed/master_metadata_utility.h
  src/include/distributed/multi_router_planner.h
  src/test/regress/expected/multi_subquery.out
Labels: needs review

#2089 Fix issue preventing multiple size function calls per query
  src/backend/distributed/master/master_metadata_utility.c
  src/test/regress/expected/multi_size_queries.out
  src/test/regress/sql/multi_size_queries.sql
Labels: backport, bug, needs review

#2103 Add co-placement check to CoPartitionedTable
  src/backend/distributed/planner/multi_physical_planner.c
  src/test/regress/expected/non_colocated_join_order.out
  src/test/regress/multi_schedule
  src/test/regress/sql/non_colocated_join_order.sql
Labels: needs review

#2097 Fix crash on Windows where there is no detail
  src/backend/distributed/commands/multi_copy.c
  src/test/regress/expected/multi_insert_select.out
Labels: needs review

#2102 ANDs are being explicit for worker queries in pushdown
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/test/regress/expected/multi_having_pushdown.out
  src/test/regress/sql/multi_having_pushdown.sql
Labels: backport, needs review

#2098 Fix cancellation of real time queries
  src/backend/distributed/executor/multi_real_time_executor.c
Labels: needs review

#2116 Close all files before trying to remove them
  src/backend/distributed/transaction/transaction_management.c
Labels: needs review

#2120 Fix write and copy functions for TaskExecution.
  src/backend/distributed/utils/citus_copyfuncs.c
  src/backend/distributed/utils/citus_outfuncs.c
Labels: needs review

#2090 Refactor logical optimizer [Phase 2] - Eliminate code duplication in `WorkerExtendedOpNode()`
  src/backend/distributed/planner/multi_logical_optimizer.c
Labels: needs review

#2117 Configure appveyor to run regression tests
  Makefile
  appveyor.yml
  citus.control
  src/backend/distributed/install.pl
  src/test/regress/pg_regress_multi.pl
Labels: needs review

#2133 Fail task in real-time executor if no placements found.
  src/backend/distributed/executor/multi_real_time_executor.c
Labels: needs review

#2123 Improve connection error reporting
  src/backend/distributed/commands/multi_copy.c
  src/backend/distributed/connection/remote_commands.c
  src/backend/distributed/executor/multi_router_executor.c
  src/backend/distributed/transaction/remote_transaction.c
  src/include/distributed/remote_transaction.h
  src/test/regress/expected/multi_modifying_xacts.out
  src/test/regress/expected/multi_replicate_reference_table.out
  src/test/regress/output/multi_alter_table_statements.source
  src/test/regress/sql/multi_replicate_reference_table.sql
Labels: needs review

#2121 Add support for (VACUUM | ANALYZE) VERBOSE
  src/backend/distributed/connection/connection_management.c
  src/backend/distributed/executor/multi_router_executor.c
  src/backend/distributed/executor/multi_utility.c
  src/backend/distributed/transaction/multi_shard_transaction.c
  src/backend/distributed/transaction/transaction_management.c
  src/include/distributed/connection_management.h
  src/include/distributed/multi_physical_planner.h
  src/test/regress/expected/multi_utilities.out
  src/test/regress/expected/multi_utilities_0.out
  src/test/regress/sql/multi_utilities.sql
Labels: needs review

#2107 Simplify optimizer [Phase 3] - Move processing each part of the query into its own functions
  src/backend/distributed/planner/extended_op_node_utils.c
  src/backend/distributed/planner/multi_logical_optimizer.c
Labels: needs review
