Repository citusdata/citus, pull requests merged in 2018-02, with the labels that each got.

#2003 Only copy distributed plan when modifying it
  src/backend/distributed/executor/multi_router_executor.c
  src/backend/distributed/planner/distributed_planner.c
Labels: performance

#1979 Handle errors that are discovered during abort
  src/backend/distributed/connection/remote_commands.c
  src/backend/distributed/transaction/remote_transaction.c
  src/include/distributed/remote_commands.h
Labels: bug, priority:high

#2007 Recursively plan subqueries in WHERE clause when FROM recurs
  src/backend/distributed/planner/multi_logical_planner.c
  src/backend/distributed/planner/recursive_planning.c
  src/include/distributed/multi_logical_planner.h
  src/test/regress/expected/multi_subquery_in_where_reference_clause.out
  src/test/regress/expected/set_operation_and_local_tables.out
  src/test/regress/expected/set_operations.out
  src/test/regress/expected/subqueries_not_supported.out
  src/test/regress/expected/subquery_and_cte.out
  src/test/regress/expected/subquery_basics.out
  src/test/regress/expected/subquery_in_where.out
  src/test/regress/expected/with_prepare.out
  src/test/regress/multi_schedule
  src/test/regress/sql/multi_subquery_in_where_reference_clause.sql
  src/test/regress/sql/set_operation_and_local_tables.sql
  src/test/regress/sql/set_operations.sql
  src/test/regress/sql/subqueries_not_supported.sql
  src/test/regress/sql/subquery_and_cte.sql
  src/test/regress/sql/subquery_basics.sql
  src/test/regress/sql/subquery_in_where.sql
  src/test/regress/sql/with_prepare.sql
Labels: needs review

#2015 Add support for json(b) aggregation
  src/backend/distributed/Makefile
  src/backend/distributed/citus--7.3-2--7.3-3.sql
  src/backend/distributed/citus.control
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/include/distributed/multi_logical_optimizer.h
  src/test/regress/expected/multi_extension.out
  src/test/regress/expected/multi_json_agg.out
  src/test/regress/expected/multi_json_object_agg.out
  src/test/regress/expected/multi_jsonb_agg.out
  src/test/regress/expected/multi_jsonb_object_agg.out
  src/test/regress/expected/subquery_in_where.out
  src/test/regress/multi_schedule
  src/test/regress/sql/multi_extension.sql
  src/test/regress/sql/multi_json_agg.sql
  src/test/regress/sql/multi_json_object_agg.sql
  src/test/regress/sql/multi_jsonb_agg.sql
  src/test/regress/sql/multi_jsonb_object_agg.sql
Labels: CLA Signed

#2023 Do not use new connection in table size functions
  src/backend/distributed/master/master_metadata_utility.c
Labels: needs review

#2016 Support non-co-located joins between subqueries
  src/backend/distributed/planner/insert_select_planner.c
  src/backend/distributed/planner/multi_logical_planner.c
  src/backend/distributed/planner/query_colocation_checker.c
  src/backend/distributed/planner/recursive_planning.c
  src/backend/distributed/planner/relation_restriction_equivalence.c
  src/include/distributed/multi_logical_planner.h
  src/include/distributed/query_colocation_checker.h
  src/include/distributed/relation_restriction_equivalence.h
  src/test/regress/expected/multi_insert_select_non_pushable_queries.out
  src/test/regress/expected/multi_mx_create_table.out
  src/test/regress/expected/multi_mx_explain.out
  src/test/regress/expected/multi_mx_explain_0.out
  src/test/regress/expected/multi_mx_router_planner.out
  src/test/regress/expected/multi_router_planner.out
  src/test/regress/expected/multi_simple_queries_0.out
  src/test/regress/expected/multi_subquery.out
  src/test/regress/expected/multi_subquery_behavioral_analytics.out
  src/test/regress/expected/multi_subquery_complex_queries.out
  src/test/regress/expected/multi_subquery_complex_reference_clause.out
  src/test/regress/expected/multi_subquery_in_where_clause.out
  src/test/regress/expected/multi_view.out
  src/test/regress/expected/non_colocated_leaf_subquery_joins.out
  src/test/regress/expected/non_colocated_subquery_joins.out
  src/test/regress/expected/set_operations.out
  src/test/regress/expected/subqueries_not_supported.out
  src/test/regress/expected/subquery_executors.out
  src/test/regress/input/multi_mx_copy_data.source
  src/test/regress/multi_schedule
  src/test/regress/output/multi_mx_copy_data.source
  src/test/regress/sql/multi_insert_select_non_pushable_queries.sql
  src/test/regress/sql/multi_mx_create_table.sql
  src/test/regress/sql/multi_mx_explain.sql
  src/test/regress/sql/multi_mx_router_planner.sql
  src/test/regress/sql/multi_router_planner.sql
  src/test/regress/sql/multi_subquery.sql
  src/test/regress/sql/multi_subquery_behavioral_analytics.sql
  src/test/regress/sql/multi_subquery_complex_queries.sql
  src/test/regress/sql/multi_subquery_complex_reference_clause.sql
  src/test/regress/sql/multi_subquery_in_where_clause.sql
  src/test/regress/sql/multi_view.sql
  src/test/regress/sql/non_colocated_leaf_subquery_joins.sql
  src/test/regress/sql/non_colocated_subquery_joins.sql
  src/test/regress/sql/set_operations.sql
  src/test/regress/sql/subqueries_not_supported.sql
  src/test/regress/sql/subquery_executors.sql
Labels: needs review

#2018 Add distinct plan after aggregation plan on master planner
  src/backend/distributed/planner/multi_master_planner.c
  src/test/regress/expected/multi_select_distinct.out
  src/test/regress/sql/multi_select_distinct.sql
Labels: backport, needs review

#2024 Fix worker query when order by aggregate is used
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/backend/distributed/planner/multi_master_planner.c
  src/test/regress/expected/multi_orderby_limit_pushdown.out
  src/test/regress/expected/multi_select_distinct.out
  src/test/regress/expected/multi_subquery.out
  src/test/regress/multi_schedule
  src/test/regress/sql/multi_complex_expressions.sql
  src/test/regress/sql/multi_orderby_limit_pushdown.sql
  src/test/regress/sql/multi_select_distinct.sql
Labels: backport, needs review

#2030 Add support for bool and bit aggregates
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/include/distributed/multi_logical_optimizer.h
  src/test/regress/expected/bool_agg.out
  src/test/regress/multi_schedule
  src/test/regress/sql/bool_agg.sql
Labels: needs review
