Repository citusdata/citus, pull requests merged in 2018-09, with the labels that each got.

#2343 Make sure that table (and metadata) is dropped before shards are dropped on Citus MX
  citus.control
  src/backend/distributed/Makefile
  src/backend/distributed/citus--8.0-2--8.0-3.sql
  src/backend/distributed/citus.control
  src/backend/distributed/commands/drop_distributed_table.c
  src/test/regress/expected/multi_extension.out
  src/test/regress/expected/multi_unsupported_worker_operations.out
  src/test/regress/sql/multi_extension.sql
  src/test/regress/sql/multi_unsupported_worker_operations.sql
Labels: needs review

#2367 Do not recover wrong distributed transactions in MX
  src/backend/distributed/transaction/transaction_recovery.c
  src/test/regress/expected/multi_mx_transaction_recovery.out
  src/test/regress/sql/multi_mx_transaction_recovery.sql
Labels: backport, bug

#2413 Fix memory leak in FinishRemoteTransactionPrepare
  src/backend/distributed/transaction/remote_transaction.c
Labels: backport
