Repository citusdata/citus, pull requests merged in 2019-10, with the labels that each got.

#3045 MX Isolation Tests for SELECT FOR UPDATE on Reference Tables
  src/test/regress/expected/isolation_ref_select_for_update_vs_all_on_mx.out
  src/test/regress/isolation_schedule
  src/test/regress/specs/isolation_ref_select_for_update_vs_all_on_mx.spec
Labels: isolation tests, mx

#3044 MX Isolation Tests for Update, Delete, Upsert on Reference Tables
  src/test/regress/expected/isolation_ref_update_delete_upsert_vs_all_on_mx.out
  src/test/regress/isolation_schedule
  src/test/regress/specs/isolation_ref_update_delete_upsert_vs_all_on_mx.spec
Labels: isolation tests, mx

#3060 MX Isolation Tests for Foreign keys from Distributrion to Reference tables vs DML
  src/test/regress/expected/isolation_dis2ref_foreign_keys_on_mx.out
  src/test/regress/isolation_schedule
  src/test/regress/specs/isolation_dis2ref_foreign_keys_on_mx.spec
Labels: isolation tests, mx

#3072 Drop the rebalancer before creating new UDFs
  src/backend/distributed/sql/citus--8.3-1--9.0-1.sql
Labels: bug

#3068 Don't block for locks in SyncMetadataToNodes()
  src/backend/distributed/metadata/metadata_sync.c
  src/backend/distributed/transaction/worker_transaction.c
  src/backend/distributed/utils/maintenanced.c
  src/backend/distributed/utils/node_metadata.c
  src/include/distributed/metadata_sync.h
  src/test/regress/expected/distributed_functions.out
  src/test/regress/sql/distributed_functions.sql
Labels: bug

#3111 Refresh Materialized View with Subquery
  src/test/regress/expected/materialized_view.out
  src/test/regress/expected/multi_view.out
  src/test/regress/multi_schedule
  src/test/regress/sql/materialized_view.sql
  src/test/regress/sql/multi_view.sql
Labels: bug, regression tests

#3114 Fix memory leak on ReceiveResults
  src/backend/distributed/executor/adaptive_executor.c
Labels: backport, bug

#3131 Do not assign InvalidOid for local execution while extracting parameters
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/executor/multi_router_executor.c
  src/include/distributed/multi_router_executor.h
  src/test/regress/expected/local_shard_execution.out
  src/test/regress/sql/local_shard_execution.sql
Labels: bug

#3129 Disallow distributed function creation when replication_model is 'statement'
  src/backend/distributed/commands/function.c
  src/test/regress/expected/distributed_functions.out
  src/test/regress/expected/distributed_procedure.out
  src/test/regress/expected/isolation_ensure_dependency_activate_node.out
  src/test/regress/expected/multi_multiuser.out
  src/test/regress/expected/multi_mx_function_call_delegation.out
  src/test/regress/specs/isolation_ensure_dependency_activate_node.spec
  src/test/regress/sql/distributed_functions.sql
  src/test/regress/sql/distributed_procedure.sql
  src/test/regress/sql/multi_multiuser.sql
  src/test/regress/sql/multi_mx_function_call_delegation.sql
Labels: backport, bug

#3137 refactor some of hard coded values in citus gucs
  src/backend/distributed/shared_library_init.c
  src/include/distributed/shared_library_init.h
  src/include/distributed/time_constants.h
Labels: refactor

#3146 Do not try to sync metadata on standby coordinator
  src/backend/distributed/utils/maintenanced.c
Labels: backport, bug
