Repository citusdata/citus, pull requests merged in 2019-12, with the labels that each got.

#3271 Fix inserts into local tables with distributed subqueries
  src/backend/distributed/planner/multi_router_planner.c
  src/test/regress/expected/dml_recursive.out
  src/test/regress/expected/multi_modifications.out
  src/test/regress/expected/multi_shard_update_delete.out
  src/test/regress/sql/multi_modifications.sql
Labels: backport, bug

#3285 rename REMOTE_TRANS_INVALID to REMOTE_TRANS_IDLE
  src/backend/distributed/connection/placement_connection.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/transaction/remote_transaction.c
  src/include/distributed/remote_transaction.h
Labels: refactor

#3283 remove unused targets from makefile
  src/test/regress/Makefile
Labels: cleanup

#3284 update contributing
  CONTRIBUTING.md
Labels: documentation

#3286 remove copyright years
  src/backend/distributed/commands/call.c
  src/backend/distributed/commands/collation.c
  src/backend/distributed/commands/dependencies.c
  src/backend/distributed/commands/function.c
  src/backend/distributed/commands/type.c
  src/backend/distributed/commands/variableset.c
  src/backend/distributed/connection/placement_connection.c
  src/backend/distributed/deparser/deparse.c
  src/backend/distributed/deparser/deparse_type_stmts.c
  src/backend/distributed/deparser/format_collate.c
  src/backend/distributed/deparser/objectaddress.c
  src/backend/distributed/deparser/qualify.c
  src/backend/distributed/deparser/qualify_type_stmt.c
  src/backend/distributed/executor/multi_task_tracker_executor.c
  src/backend/distributed/master/master_create_shards.c
  src/backend/distributed/master/master_delete_protocol.c
  src/backend/distributed/master/master_metadata_utility.c
  src/backend/distributed/master/master_repair_shards.c
  src/backend/distributed/master/master_split_shards.c
  src/backend/distributed/master/master_stage_protocol.c
  src/backend/distributed/master/master_truncate.c
  src/backend/distributed/master/shard_rebalancer.c
  src/backend/distributed/metadata/dependency.c
  src/backend/distributed/metadata/distobject.c
  src/backend/distributed/planner/deparse_shard_query.c
  src/backend/distributed/planner/fast_path_router_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/planner/shard_pruning.c
  src/backend/distributed/test/blackhole_am.c
  src/backend/distributed/test/colocation_utils.c
  src/backend/distributed/test/create_shards.c
  src/backend/distributed/test/deparse_shard_query.c
  src/backend/distributed/test/distributed_deadlock_detection.c
  src/backend/distributed/test/distribution_metadata.c
  src/backend/distributed/test/fake_fdw.c
  src/backend/distributed/test/metadata_sync.c
  src/backend/distributed/test/prune_shard_list.c
  src/backend/distributed/test/relation_access_tracking.c
  src/backend/distributed/utils/acquire_lock.c
  src/backend/distributed/utils/colocation_utils.c
  src/backend/distributed/utils/listutils.c
  src/backend/distributed/utils/reference_table_utils.c
  src/backend/distributed/utils/shardinterval_utils.c
  src/backend/distributed/worker/worker_create_or_replace.c
  src/include/distributed/citus_acquire_lock.h
  src/include/distributed/colocation_utils.h
  src/include/distributed/deparse_shard_query.h
  src/include/distributed/deparser.h
  src/include/distributed/enterprise.h
  src/include/distributed/listutils.h
  src/include/distributed/local_executor.h
  src/include/distributed/master_metadata_utility.h
  src/include/distributed/metadata/dependency.h
  src/include/distributed/metadata/distobject.h
  src/include/distributed/metadata/namespace.h
  src/include/distributed/metadata/pg_dist_object.h
  src/include/distributed/multi_router_planner.h
  src/include/distributed/reference_table_utils.h
  src/include/distributed/shard_pruning.h
  src/include/distributed/shardinterval_utils.h
Labels: cleanup

#3280 Fix the way we check for local/reference table joins in the executor
  src/backend/distributed/executor/multi_executor.c
  src/backend/distributed/planner/distributed_planner.c
  src/test/regress/expected/multi_test_helpers.out
  src/test/regress/expected/replicate_reference_tables_to_coordinator.out
  src/test/regress/sql/multi_test_helpers.sql
  src/test/regress/sql/replicate_reference_tables_to_coordinator.sql
Labels: backport

#3289 not continue in sequential execution if a cancellation is received
  src/backend/distributed/executor/adaptive_executor.c
  src/test/regress/expected/failure_multi_row_insert.out
  src/test/regress/sql/failure_multi_row_insert.sql
Labels: bug

#3290 add IsCancellationReceived utility function
  src/backend/distributed/connection/connection_management.c
  src/backend/distributed/connection/remote_commands.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/utils/cancel_utils.c
  src/include/distributed/cancel_utils.h
Labels: refactor

#3209 refactor some parts in adaptive executor
  src/backend/distributed/executor/adaptive_executor.c
Labels: refactor

#3262 Fix error in DML with NULL expression in where clause
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/test/regress/expected/multi_modifications.out
  src/test/regress/sql/multi_modifications.sql
Labels: backport, bug

#3287 refactor extract distributed insert values rte
  src/backend/distributed/planner/multi_router_planner.c
Labels: refactor

#3299 Fix crash in IN (.., NULL) queries
  src/backend/distributed/planner/shard_pruning.c
  src/test/regress/expected/multi_router_planner.out
  src/test/regress/sql/multi_router_planner.sql
Labels: backport, bug

#3297 refactor MapTaskList in multi physical planner
  src/backend/distributed/planner/multi_physical_planner.c
Labels: refactor

#3293 replace `Begin` words in coordinated transactions with `Use`
  src/backend/distributed/commands/multi_copy.c
  src/backend/distributed/commands/truncate.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/intermediate_results.c
  src/backend/distributed/executor/subplan_execution.c
  src/backend/distributed/master/master_delete_protocol.c
  src/backend/distributed/master/master_stage_protocol.c
  src/backend/distributed/planner/multi_explain.c
  src/backend/distributed/transaction/backend_data.c
  src/backend/distributed/transaction/transaction_management.c
  src/backend/distributed/transaction/worker_transaction.c
  src/backend/distributed/utils/resource_lock.c
  src/include/distributed/transaction_management.h
Labels: refactor

#3310 add circleci build status
  README.md
Labels: documentation

#3309 add code coverage badge
  README.md
Labels: documentation

#3302 Fix a crash when calling a distributed function from PL/pgSQL
  src/backend/distributed/planner/distributed_planner.c
  src/backend/distributed/planner/function_call_delegation.c
  src/backend/distributed/transaction/transaction_management.c
  src/include/distributed/distributed_planner.h
  src/test/regress/expected/distributed_functions.out
  src/test/regress/sql/distributed_functions.sql
Labels: backport, bug

#3311 FIX: Make sure to correctly decrement ExecutorLevel
  src/backend/distributed/executor/multi_executor.c
  src/backend/distributed/transaction/transaction_management.c
Labels: backport

#3301 Use any available non-data connection for intermediate results
  src/backend/distributed/connection/connection_management.c
  src/backend/distributed/executor/intermediate_results.c
  src/include/distributed/connection_management.h
  src/test/regress/expected/with_transactions.out
  src/test/regress/sql/with_transactions.sql
Labels: backport, bug

#3169 Add adaptive executor support for repartition joins
  src/backend/distributed/commands/call.c
  src/backend/distributed/connection/connection_management.c
  src/backend/distributed/connection/remote_commands.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/directed_acylic_graph_execution.c
  src/backend/distributed/executor/insert_select_executor.c
  src/backend/distributed/executor/multi_server_executor.c
  src/backend/distributed/executor/multi_task_tracker_executor.c
  src/backend/distributed/executor/repartition_join_execution.c
  src/backend/distributed/master/master_stage_protocol.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/shared_library_init.c
  src/backend/distributed/sql/citus--9.0-2--9.1-1.sql
  src/backend/distributed/sql/udfs/worker_create_schema/9.1-1.sql
  src/backend/distributed/sql/udfs/worker_create_schema/latest.sql
  src/backend/distributed/sql/udfs/worker_repartition_cleanup/9.1-1.sql
  src/backend/distributed/sql/udfs/worker_repartition_cleanup/latest.sql
  src/backend/distributed/transaction/transaction_management.c
  src/backend/distributed/transaction/worker_transaction.c
  src/backend/distributed/worker/task_tracker.c
  src/backend/distributed/worker/task_tracker_protocol.c
  src/backend/distributed/worker/worker_merge_protocol.c
  src/include/distributed/adaptive_executor.h
  src/include/distributed/connection_management.h
  src/include/distributed/directed_acylic_graph_execution.h
  src/include/distributed/multi_server_executor.h
  src/include/distributed/multi_task_tracker_executor.h
  src/include/distributed/repartition_join_execution.h
  src/include/distributed/task_tracker.h
  src/include/distributed/task_tracker_protocol.h
  src/include/distributed/worker_protocol.h
  src/include/distributed/worker_transaction.h
  src/test/regress/expected/adaptive_executor_repartition.out
  src/test/regress/expected/limit_intermediate_size.out
  src/test/regress/expected/multi_null_minmax_value_pruning.out
  src/test/regress/expected/multi_subquery_complex_queries.out
  src/test/regress/expected/non_colocated_join_order.out
  src/test/regress/expected/non_colocated_leaf_subquery_joins.out
  src/test/regress/expected/non_colocated_subquery_joins.out
  src/test/regress/expected/recursive_dml_with_different_planners_executors.out
  src/test/regress/expected/set_operation_and_local_tables.out
  src/test/regress/expected/set_operations.out
  src/test/regress/expected/subquery_executors.out
  src/test/regress/expected/subquery_partitioning.out
  src/test/regress/expected/subquery_view.out
  src/test/regress/multi_schedule
  src/test/regress/sql/adaptive_executor_repartition.sql
  src/test/regress/sql/limit_intermediate_size.sql
  src/test/regress/sql/set_operation_and_local_tables.sql
  src/test/regress/sql/with_executors.sql
Labels: feature

#3308 Fix error in distributed queries when shards are on the coordinator
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/test/regress/expected/coordinator_shouldhaveshards.out
  src/test/regress/multi_schedule
  src/test/regress/sql/coordinator_shouldhaveshards.sql
Labels: bug

#3334 Fix inconsistent shard metadata issue
  src/backend/distributed/metadata/metadata_cache.c
  src/test/regress/expected/multi_cache_invalidation.out
  src/test/regress/sql/multi_cache_invalidation.sql
Labels: bug

#3307 Do not repeat GROUP BY distribution_column on coordinator
  src/backend/distributed/planner/extended_op_node_utils.c
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/test/regress/expected/aggregate_support.out
  src/test/regress/expected/custom_aggregate_support.out
  src/test/regress/expected/multi_having_pushdown.out
  src/test/regress/expected/multi_orderby_limit_pushdown.out
  src/test/regress/expected/multi_repartition_join_planning.out
  src/test/regress/expected/multi_select_distinct.out
  src/test/regress/expected/multi_view.out
  src/test/regress/expected/subqueries_not_supported.out
  src/test/regress/output/multi_complex_count_distinct.source
  src/test/regress/sql/aggregate_support.sql
  src/test/regress/sql/subqueries_not_supported.sql
Labels: performance
