Repository citusdata/citus, pull requests merged in 2020-09, with the labels that each got.

#4132 Introduce cache entry/table utilities
  src/backend/distributed/commands/call.c
  src/backend/distributed/commands/create_distributed_table.c
  src/backend/distributed/commands/foreign_constraint.c
  src/backend/distributed/commands/function.c
  src/backend/distributed/commands/index.c
  src/backend/distributed/commands/multi_copy.c
  src/backend/distributed/commands/schema.c
  src/backend/distributed/commands/table.c
  src/backend/distributed/commands/truncate.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/distributed_execution_locks.c
  src/backend/distributed/executor/distributed_intermediate_results.c
  src/backend/distributed/executor/insert_select_executor.c
  src/backend/distributed/metadata/metadata_cache.c
  src/backend/distributed/metadata/metadata_sync.c
  src/backend/distributed/metadata/metadata_utility.c
  src/backend/distributed/metadata/node_metadata.c
  src/backend/distributed/operations/delete_protocol.c
  src/backend/distributed/operations/repair_shards.c
  src/backend/distributed/operations/stage_protocol.c
  src/backend/distributed/planner/deparse_shard_query.c
  src/backend/distributed/planner/distributed_planner.c
  src/backend/distributed/planner/extended_op_node_utils.c
  src/backend/distributed/planner/fast_path_router_planner.c
  src/backend/distributed/planner/insert_select_planner.c
  src/backend/distributed/planner/multi_join_order.c
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/backend/distributed/planner/multi_logical_planner.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/planner/query_colocation_checker.c
  src/backend/distributed/planner/query_pushdown_planning.c
  src/backend/distributed/planner/relation_restriction_equivalence.c
  src/backend/distributed/planner/shard_pruning.c
  src/backend/distributed/test/distributed_intermediate_results.c
  src/backend/distributed/transaction/relation_access_tracking.c
  src/backend/distributed/utils/colocation_utils.c
  src/backend/distributed/utils/reference_table_utils.c
  src/backend/distributed/utils/resource_lock.c
  src/backend/distributed/utils/shard_utils.c
  src/backend/distributed/utils/shardinterval_utils.c
  src/backend/distributed/utils/statistics_collection.c
  src/include/distributed/distributed_planner.h
  src/include/distributed/metadata_cache.h
  src/include/distributed/metadata_utility.h
  src/include/distributed/reference_table_utils.h
Labels: refactor

#4171 Fix EXPLAIN ANALYZE truncation
  src/backend/distributed/planner/multi_explain.c
  src/test/regress/expected/multi_explain.out
  src/test/regress/sql/multi_explain.sql
Labels: backport, bug

#4127 Not allow removing a single node with ref tables
  src/backend/distributed/metadata/metadata_cache.c
  src/backend/distributed/metadata/node_metadata.c
  src/backend/distributed/operations/worker_node_manager.c
  src/include/distributed/metadata_cache.h
  src/include/distributed/worker_manager.h
  src/test/regress/expected/citus_local_tables.out
  src/test/regress/expected/failure_add_disable_node.out
  src/test/regress/expected/isolation_create_citus_local_table.out
  src/test/regress/expected/isolation_create_table_vs_add_remove_node.out
  src/test/regress/expected/multi_cluster_management.out
  src/test/regress/expected/multi_remove_node_reference_table.out
  src/test/regress/expected/single_node.out
  src/test/regress/sql/multi_remove_node_reference_table.sql
  src/test/regress/sql/single_node.sql
Labels: bug

#4184 Not take ShareUpdateExlusiveLock on pg_dist_transaction
  src/backend/distributed/transaction/transaction_recovery.c
  src/backend/distributed/utils/resource_lock.c
  src/include/distributed/resource_lock.h
Labels: backport, bug

#4167 Improve the robustness of function call delegation
  src/backend/distributed/commands/call.c
  src/backend/distributed/metadata/node_metadata.c
  src/backend/distributed/planner/function_call_delegation.c
  src/test/regress/expected/single_node.out
  src/test/regress/sql/single_node.sql
Labels: single node

#4181 Merge enterprise branch if it exists
  ci/check_enterprise_merge.sh
Labels: bug

#4173 Fix create index concurrently crash with local execution
  src/backend/distributed/commands/index.c
  src/backend/distributed/commands/utility_hook.c
  src/include/distributed/commands.h
  src/include/distributed/commands/utility_hook.h
  src/test/regress/expected/replicate_reference_tables_to_coordinator.out
  src/test/regress/sql/replicate_reference_tables_to_coordinator.sql
Labels: bug, single node
