Repository citusdata/citus, pull requests merged in 2020-05, with the labels that each got.

#3814 Fix a bug that wrapped target list entries in any_value incorrectly
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/planner/query_pushdown_planning.c
  src/include/distributed/multi_physical_planner.h
  src/test/regress/expected/subquery_complex_target_list.out
  src/test/regress/sql/subquery_complex_target_list.sql
Labels: bug

#3696 remove ExecuteUtilityTaskListWithoutResults
  src/backend/distributed/commands/utility_hook.c
  src/backend/distributed/commands/vacuum.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/master/master_truncate.c
  src/include/distributed/adaptive_executor.h
  src/include/distributed/local_executor.h
  src/include/distributed/multi_executor.h
Labels: refactor

#3760 not wait forever for metadata sync in tests
  src/test/regress/expected/distributed_functions.out
  src/test/regress/expected/distributed_procedure.out
  src/test/regress/expected/multi_multiuser.out
  src/test/regress/expected/multi_mx_add_coordinator.out
  src/test/regress/expected/multi_mx_function_table_reference.out
  src/test/regress/expected/multi_mx_node_metadata.out
  src/test/regress/expected/multi_test_helpers_superuser.out
  src/test/regress/sql/distributed_functions.sql
  src/test/regress/sql/distributed_procedure.sql
  src/test/regress/sql/multi_multiuser.sql
  src/test/regress/sql/multi_mx_add_coordinator.sql
  src/test/regress/sql/multi_mx_function_table_reference.sql
  src/test/regress/sql/multi_mx_node_metadata.sql
  src/test/regress/sql/multi_test_helpers_superuser.sql
Labels: regression tests

#3842 Rename AppropriateReplicationModel -> DecideReplicationModel
  src/backend/distributed/commands/create_distributed_table.c
Labels: refactor

#3846 Refactor the methods accessing to pg_constraint
  src/backend/distributed/commands/foreign_constraint.c
  src/backend/distributed/master/master_repair_shards.c
  src/backend/distributed/master/master_stage_protocol.c
  src/backend/distributed/metadata/metadata_sync.c
  src/include/distributed/commands.h
Labels: refactor

#3834 Prep routing modifying ctes
  src/backend/distributed/commands/call.c
  src/backend/distributed/commands/function.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/distributed_execution_locks.c
  src/backend/distributed/executor/distributed_intermediate_results.c
  src/backend/distributed/executor/insert_select_executor.c
  src/backend/distributed/executor/multi_task_tracker_executor.c
  src/backend/distributed/planner/distributed_planner.c
  src/backend/distributed/planner/function_call_delegation.c
  src/backend/distributed/planner/insert_select_planner.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/transaction/relation_access_tracking.c
  src/backend/distributed/utils/citus_clauses.c
  src/backend/distributed/utils/citus_copyfuncs.c
  src/backend/distributed/utils/citus_outfuncs.c
  src/include/distributed/distributed_planner.h
  src/include/distributed/multi_executor.h
  src/include/distributed/multi_physical_planner.h
Labels: refactor

#3857 use RelationGetPartitionDesc to be more safe
  src/backend/distributed/utils/multi_partitioning_utils.c
Labels: bug
