Repository citusdata/citus, pull requests merged in 2020-07, with the labels that each got.

#3978 Fix explain subplan duration
  src/backend/distributed/executor/subplan_execution.c
Labels: bug

#4003 rename node/worker utilities
  src/backend/distributed/commands/dependencies.c
  src/backend/distributed/commands/function.c
  src/backend/distributed/executor/intermediate_results.c
  src/backend/distributed/executor/multi_server_executor.c
  src/backend/distributed/executor/multi_task_tracker_executor.c
  src/backend/distributed/metadata/metadata_sync.c
  src/backend/distributed/operations/citus_create_restore_point.c
  src/backend/distributed/operations/node_protocol.c
  src/backend/distributed/operations/worker_node_manager.c
  src/backend/distributed/planner/intermediate_result_pruning.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/test/metadata_sync.c
  src/backend/distributed/transaction/backend_data.c
  src/backend/distributed/transaction/citus_dist_stat_activity.c
  src/backend/distributed/transaction/worker_transaction.c
  src/backend/distributed/utils/resource_lock.c
  src/backend/distributed/utils/statistics_collection.c
  src/include/distributed/worker_manager.h
Labels: refactor

#4000 Fix a memory leak in subtransaction handling
  src/backend/distributed/commands/variableset.c
  src/backend/distributed/test/xact_stats.c
  src/backend/distributed/transaction/transaction_management.c
  src/test/regress/expected/multi_subtransactions.out
  src/test/regress/expected/multi_test_helpers_superuser.out
  src/test/regress/sql/multi_subtransactions.sql
  src/test/regress/sql/multi_test_helpers_superuser.sql
Labels: backport

#4015 rename TargetWorkerSet enums
  src/backend/distributed/commands/collation.c
  src/backend/distributed/commands/extension.c
  src/backend/distributed/commands/function.c
  src/backend/distributed/commands/role.c
  src/backend/distributed/commands/schema.c
  src/backend/distributed/commands/type.c
  src/backend/distributed/executor/repartition_join_execution.c
  src/backend/distributed/transaction/worker_transaction.c
  src/include/distributed/worker_transaction.h
Labels: refactor

#4017 remove unused worker methods
  src/backend/distributed/transaction/worker_transaction.c
  src/include/distributed/worker_transaction.h
Labels: cleanup

#4018 remove no-op check in TaskListRequires2PC
  src/backend/distributed/executor/adaptive_executor.c
Labels: cleanup

#4011 force aliases in deparsing for queries with anonymous column references
  src/backend/distributed/deparser/ruleutils_11.c
  src/backend/distributed/deparser/ruleutils_12.c
  src/test/regress/expected/anonymous_columns.out
  src/test/regress/expected/cte_inline.out
  src/test/regress/expected/cte_inline_0.out
  src/test/regress/expected/dml_recursive.out
  src/test/regress/expected/multi_insert_select.out
  src/test/regress/expected/multi_subquery_complex_reference_clause.out
  src/test/regress/expected/with_modifying.out
  src/test/regress/multi_schedule
  src/test/regress/sql/anonymous_columns.sql
Labels: backport, bug

#4005 Send commands to coordinator when it is added as a worker
  src/backend/distributed/executor/multi_server_executor.c
  src/backend/distributed/executor/multi_task_tracker_executor.c
  src/backend/distributed/executor/repartition_join_execution.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/transaction/worker_transaction.c
  src/include/distributed/worker_transaction.h
  src/test/regress/expected/coordinator_shouldhaveshards.out
  src/test/regress/expected/follower_single_node.out
  src/test/regress/expected/multi_follower_select_statements.out
  src/test/regress/expected/single_node.out
  src/test/regress/sql/coordinator_shouldhaveshards.sql
  src/test/regress/sql/follower_single_node.sql
  src/test/regress/sql/multi_follower_select_statements.sql
  src/test/regress/sql/single_node.sql
Labels: bug

#3698 test local coordinator reference-distributed table join
  src/test/regress/expected/coordinator_shouldhaveshards.out
  src/test/regress/sql/coordinator_shouldhaveshards.sql
Labels: regression tests

#4029 fix flappy tests due to indeterministic order of test output
  src/test/regress/expected/anonymous_columns.out
  src/test/regress/sql/anonymous_columns.sql
Labels: backport

#4036 Prevent integer overflow in FindShardIntervalIndex
  src/backend/distributed/utils/shardinterval_utils.c
Labels: backport, bug

#4053 Unify node sort ordering
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/operations/worker_node_manager.c
  src/include/distributed/worker_manager.h
Labels: refactor

#4052 Move executor specific logic to a function
  src/backend/distributed/connection/shared_connection_stats.c
  src/backend/distributed/executor/adaptive_executor.c
  src/include/distributed/shared_connection_stats.h
Labels: refactor

#3298 separate the logic in ManageWorkerPool
  src/backend/distributed/executor/adaptive_executor.c
Labels: refactor

#4058 Fixes the ALTER TABLE IF EXISTS SET SCHEMA bug
  src/backend/distributed/commands/table.c
  src/test/regress/expected/multi_schema_support.out
  src/test/regress/sql/multi_schema_support.sql
Labels: backport

#4061 Fix int32 overflow and use PG macros for INT32_XX
  src/backend/distributed/commands/multi_copy.c
  src/backend/distributed/metadata/metadata_cache.c
  src/backend/distributed/operations/create_shards.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/test/distribution_metadata.c
  src/backend/distributed/utils/shardinterval_utils.c
  src/backend/distributed/worker/worker_partition_protocol.c
  src/include/distributed/shardinterval_utils.h
Labels: backport, bug

#4060 Fixes CREATE INDEX CONCURRENTLY bug
  src/backend/distributed/commands/index.c
  src/test/regress/expected/multi_index_statements.out
  src/test/regress/sql/multi_index_statements.sql
Labels: backport

#4039 propagation of CHECK statements to workers with parentheses
  src/backend/distributed/deparser/citus_ruleutils.c
  src/test/regress/expected/multi_generate_ddl_commands.out
  src/test/regress/sql/multi_generate_ddl_commands.sql
Labels: bug
