Repository citusdata/citus, pull requests merged in 2020-11, with the labels that each got.

#4293 Fix uninitialized variable
  src/backend/distributed/deparser/ruleutils_13.c
Labels: bug

#4294 Fix relkind checks in planner for relkinds other than RELKIND_RELATION
  src/backend/distributed/planner/distributed_planner.c
  src/backend/distributed/planner/multi_logical_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/test/regress/expected/mixed_relkind_tests.out
  src/test/regress/expected/multi_test_helpers.out
  src/test/regress/multi_schedule
  src/test/regress/sql/mixed_relkind_tests.sql
  src/test/regress/sql/multi_test_helpers.sql
Labels: bug

#4325 Enable parallel query on EXPLAIN ANALYZE
  src/backend/distributed/planner/multi_explain.c
Labels: backport, bug

#4331 Do not execute subplans multiple times with cursors
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/citus_custom_scan.c
  src/include/distributed/citus_custom_scan.h
  src/test/regress/expected/cursors.out
  src/test/regress/multi_schedule
  src/test/regress/sql/cursors.sql
Labels: backport, bug

#4344 Do not cache all the distributed table metadata during CitusTableTypedList()
  src/backend/distributed/metadata/metadata_cache.c
  src/test/regress/bin/normalize.sed
  src/test/regress/expected/insert_select_repartition.out
Labels: backport, bug

#4272 Refactor PreprocessIndexStmt
  src/backend/distributed/commands/index.c
  src/backend/distributed/utils/relation_utils.c
  src/include/distributed/relation_utils.h
Labels: refactor

#4326 Fix constraint name for local execution
  src/backend/distributed/planner/deparse_shard_query.c
  src/test/regress/expected/single_node.out
  src/test/regress/sql/single_node.sql
Labels: bug, single node

#4362 Handle invalid connection hash entries
  src/backend/distributed/connection/connection_management.c
  src/include/distributed/connection_management.h
Labels: backport, bug
