Repository citusdata/citus, pull requests merged in 2020-12, with the labels that each got.

#4373 Propagate alter schema rename
  src/backend/distributed/commands/distribute_object_ops.c
  src/backend/distributed/commands/schema.c
  src/backend/distributed/deparser/deparse_schema_stmts.c
  src/include/distributed/commands.h
  src/include/distributed/deparser.h
  src/test/regress/expected/multi_schema_support.out
  src/test/regress/sql/multi_schema_support.sql
Labels: DDL, bug

#4375 Columnar: Fix VACUUM for empty tables
  src/backend/columnar/cstore_metadata_tables.c
  src/backend/columnar/cstore_tableam.c
  src/test/regress/columnar_am_schedule
  src/test/regress/expected/am_empty.out
  src/test/regress/sql/am_empty.sql
Labels: columnar

#4386 Columnar: track decompressed length in metadata
  src/backend/columnar/cstore_metadata_tables.c
  src/backend/columnar/cstore_tableam.c
  src/backend/columnar/cstore_writer.c
  src/backend/columnar/sql/columnar--9.5-1--10.0-1.sql
  src/include/columnar/cstore.h
  src/test/regress/expected/am_empty.out
  src/test/regress/expected/am_vacuum.out
  src/test/regress/expected/am_vacuum_vs_insert.out
  src/test/regress/expected/upgrade_columnar_after.out
  src/test/regress/sql/am_vacuum.sql
Labels: columnar

#4337 Add LZ4 compression to columnar
  configure
  configure.in
  src/backend/columnar/cstore.c
  src/backend/columnar/cstore_compression.c
  src/backend/columnar/cstore_reader.c
  src/backend/columnar/cstore_tableam.c
  src/include/citus_config.h.in
  src/include/citus_version.h.in
  src/include/columnar/cstore.h
  src/test/regress/columnar_am_schedule
  src/test/regress/expected/am_create.out
  src/test/regress/expected/am_empty.out
  src/test/regress/expected/am_lz4.out
  src/test/regress/expected/am_lz4_0.out
  src/test/regress/expected/am_vacuum.out
  src/test/regress/expected/am_vacuum_vs_insert.out
  src/test/regress/sql/am_create.sql
  src/test/regress/sql/am_lz4.sql
Labels: columnar

#4399 Columnar: Make compression level configurable
  src/backend/columnar/cstore.c
  src/backend/columnar/cstore_compression.c
  src/backend/columnar/cstore_metadata_tables.c
  src/backend/columnar/cstore_tableam.c
  src/backend/columnar/cstore_writer.c
  src/backend/columnar/sql/columnar--9.5-1--10.0-1.sql
  src/backend/columnar/sql/downgrades/columnar--10.0-1--9.5-1.sql
  src/backend/columnar/sql/udfs/alter_columnar_table_reset/10.0-1.sql
  src/backend/columnar/sql/udfs/alter_columnar_table_reset/latest.sql
  src/backend/columnar/sql/udfs/alter_columnar_table_set/10.0-1.sql
  src/backend/columnar/sql/udfs/alter_columnar_table_set/latest.sql
  src/backend/columnar/sql/udfs/columnar_ensure_objects_exist/10.0-1.sql
  src/backend/columnar/sql/udfs/columnar_ensure_objects_exist/latest.sql
  src/backend/columnar/write_state_management.c
  src/include/columnar/cstore.h
  src/test/regress/expected/am_empty.out
  src/test/regress/expected/am_matview.out
  src/test/regress/expected/am_tableoptions.out
  src/test/regress/expected/am_zstd.out
  src/test/regress/expected/columnar_citus_integration.out
  src/test/regress/expected/multi_extension.out
  src/test/regress/expected/upgrade_columnar_after.out
  src/test/regress/expected/upgrade_columnar_before.out
  src/test/regress/expected/upgrade_list_citus_objects.out
  src/test/regress/sql/am_tableoptions.sql
  src/test/regress/sql/am_zstd.sql
  src/test/regress/sql/columnar_citus_integration.sql
  src/test/regress/sql/upgrade_columnar_before.sql
Labels: columnar

#4403 Columnar: set default compression as zstd if available
  src/backend/columnar/cstore.c
  src/test/regress/expected/am_matview.out
  src/test/regress/expected/am_tableoptions.out
  src/test/regress/expected/am_vacuum.out
  src/test/regress/expected/columnar_citus_integration.out
  src/test/regress/spec/am_vacuum_vs_insert.spec
  src/test/regress/sql/am_matview.sql
  src/test/regress/sql/am_tableoptions.sql
  src/test/regress/sql/am_vacuum.sql
  src/test/regress/sql/columnar_citus_integration.sql
Labels: columnar

#4407 Columnar: Fix ANALYZE for large number of rows.
  src/backend/columnar/cstore_tableam.c
  src/test/regress/expected/am_analyze.out
  src/test/regress/sql/am_analyze.sql
Labels: columnar

#4360 Support co-located/recurring sublinks in the target list
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/backend/distributed/planner/multi_logical_planner.c
  src/backend/distributed/planner/query_pushdown_planning.c
  src/include/distributed/query_pushdown_planning.h
  src/test/regress/expected/cte_inline.out
  src/test/regress/expected/cte_inline_0.out
  src/test/regress/expected/multi_insert_select.out
  src/test/regress/expected/multi_mx_router_planner.out
  src/test/regress/expected/multi_router_planner.out
  src/test/regress/expected/multi_router_planner_fast_path.out
  src/test/regress/expected/multi_simple_queries.out
  src/test/regress/expected/multi_subquery.out
  src/test/regress/expected/multi_subquery_in_where_reference_clause.out
  src/test/regress/expected/multi_utility_statements.out
  src/test/regress/expected/subquery_in_targetlist.out
  src/test/regress/expected/subquery_in_where.out
  src/test/regress/expected/with_basics.out
  src/test/regress/multi_schedule
  src/test/regress/sql/cte_inline.sql
  src/test/regress/sql/multi_subquery.sql
  src/test/regress/sql/subquery_in_targetlist.sql
  src/test/regress/sql/with_basics.sql
Labels: sql

#4385 Support co-located/recurring correlated subqueries
  src/backend/distributed/planner/query_pushdown_planning.c
  src/backend/distributed/planner/recursive_planning.c
  src/include/distributed/recursive_planning.h
  src/test/regress/expected/multi_insert_select_window.out
  src/test/regress/expected/multi_mx_router_planner.out
  src/test/regress/expected/multi_router_planner.out
  src/test/regress/expected/multi_router_planner_fast_path.out
  src/test/regress/expected/multi_subquery_complex_queries.out
  src/test/regress/expected/multi_subquery_in_where_clause.out
  src/test/regress/expected/subqueries_not_supported.out
  src/test/regress/expected/subquery_in_targetlist.out
  src/test/regress/expected/subquery_in_where.out
  src/test/regress/expected/with_set_operations.out
  src/test/regress/sql/multi_mx_router_planner.sql
  src/test/regress/sql/multi_subquery_complex_queries.sql
  src/test/regress/sql/subqueries_not_supported.sql
  src/test/regress/sql/subquery_in_where.sql
Labels: sql

#4418 Reliably detect local tables in router queries in 9.4
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/planner/recursive_planning.c
  src/include/distributed/recursive_planning.h
  src/test/regress/expected/multi_router_planner.out
  src/test/regress/sql/multi_router_planner.sql
Labels: backport, bug

#4395 Propagate create statistics
  src/backend/distributed/commands/dependencies.c
  src/backend/distributed/commands/distribute_object_ops.c
  src/backend/distributed/commands/statistics.c
  src/backend/distributed/deparser/deparse_schema_stmts.c
  src/backend/distributed/deparser/deparse_statistics_stmts.c
  src/backend/distributed/deparser/qualify_statistics_stmt.c
  src/backend/distributed/deparser/ruleutils_11.c
  src/backend/distributed/deparser/ruleutils_12.c
  src/backend/distributed/deparser/ruleutils_13.c
  src/backend/distributed/metadata/dependency.c
  src/backend/distributed/operations/node_protocol.c
  src/backend/distributed/relay/relay_event_utility.c
  src/include/distributed/citus_ruleutils.h
  src/include/distributed/commands.h
  src/include/distributed/deparser.h
  src/test/regress/expected/propagate_statistics.out
  src/test/regress/multi_schedule
  src/test/regress/sql/propagate_statistics.sql
Labels: enhancement

#4417 Rework our CI specifications
  .circleci/config.yml
  ci/README.md
  ci/build-citus.sh
  src/test/regress/expected/follower_single_node.out
  src/test/regress/expected/join_pushdown.out
  src/test/regress/expected/multi_follower_dml.out
  src/test/regress/expected/multi_follower_select_statements.out
  src/test/regress/multi_schedule
  src/test/regress/sql/follower_single_node.sql
  src/test/regress/sql/join_pushdown.sql
  src/test/regress/sql/multi_follower_dml.sql
  src/test/regress/sql/multi_follower_select_statements.sql
Labels: regression tests

#4426 Fix attribute numbers in subquery conversions
  src/backend/distributed/planner/query_colocation_checker.c
  src/backend/distributed/planner/relation_restriction_equivalence.c
  src/test/regress/expected/citus_local_dist_joins.out
  src/test/regress/expected/citus_local_tables_queries.out
  src/test/regress/expected/local_dist_join_mixed.out
  src/test/regress/expected/local_table_join.out
  src/test/regress/expected/mixed_relkind_tests.out
  src/test/regress/sql/local_dist_join_mixed.sql
  src/test/regress/sql/local_table_join.sql
Labels: bug

#4402 Columnar: enable zstd & lz4 compilation by default
  configure
  configure.in
  src/test/regress/expected/am_lz4.out
  src/test/regress/expected/am_zstd.out
  src/test/regress/sql/am_lz4.sql
  src/test/regress/sql/am_zstd.sql
Labels: columnar

#4437 Collapse Citus 7.* scripts into Citus 8.0-1
  src/backend/distributed/sql/citus--7.0-1--7.0-2.sql
  src/backend/distributed/sql/citus--7.0-10--7.0-11.sql
  src/backend/distributed/sql/citus--7.0-11--7.0-12.sql
  src/backend/distributed/sql/citus--7.0-12--7.0-13.sql
  src/backend/distributed/sql/citus--7.0-13--7.0-14.sql
  src/backend/distributed/sql/citus--7.0-14--7.0-15.sql
  src/backend/distributed/sql/citus--7.0-15--7.1-1.sql
  src/backend/distributed/sql/citus--7.0-2--7.0-3.sql
  src/backend/distributed/sql/citus--7.0-3--7.0-4.sql
  src/backend/distributed/sql/citus--7.0-4--7.0-5.sql
  src/backend/distributed/sql/citus--7.0-5--7.0-6.sql
  src/backend/distributed/sql/citus--7.0-6--7.0-7.sql
  src/backend/distributed/sql/citus--7.0-7--7.0-8.sql
  src/backend/distributed/sql/citus--7.0-8--7.0-9.sql
  src/backend/distributed/sql/citus--7.0-9--7.0-10.sql
  src/backend/distributed/sql/citus--7.1-1--7.1-2.sql
  src/backend/distributed/sql/citus--7.1-2--7.1-3.sql
  src/backend/distributed/sql/citus--7.1-3--7.1-4.sql
  src/backend/distributed/sql/citus--7.1-4--7.2-1.sql
  src/backend/distributed/sql/citus--7.2-1--7.2-2.sql
  src/backend/distributed/sql/citus--7.2-2--7.2-3.sql
  src/backend/distributed/sql/citus--7.2-3--7.3-1.sql
  src/backend/distributed/sql/citus--7.3-1--7.3-2.sql
  src/backend/distributed/sql/citus--7.3-2--7.3-3.sql
  src/backend/distributed/sql/citus--7.3-3--7.4-1.sql
  src/backend/distributed/sql/citus--7.4-1--7.4-2.sql
  src/backend/distributed/sql/citus--7.4-2--7.4-3.sql
  src/backend/distributed/sql/citus--7.4-3--7.5-1.sql
  src/backend/distributed/sql/citus--7.5-1--7.5-2.sql
  src/backend/distributed/sql/citus--7.5-2--7.5-3.sql
  src/backend/distributed/sql/citus--7.5-3--7.5-4.sql
  src/backend/distributed/sql/citus--7.5-4--7.5-5.sql
  src/backend/distributed/sql/citus--7.5-5--7.5-6.sql
  src/backend/distributed/sql/citus--7.5-6--7.5-7.sql
  src/backend/distributed/sql/citus--7.5-7--8.0-1.sql
  src/backend/distributed/sql/citus--8.0-1.sql
  src/test/regress/expected/multi_703_upgrade.out
  src/test/regress/expected/multi_extension.out
  src/test/regress/expected/multi_extension_0.out
  src/test/regress/multi_schedule
  src/test/regress/sql/multi_703_upgrade.sql
  src/test/regress/sql/multi_extension.sql
Labels: technical debt

#4273 Support CREATE INDEX commands without index name on citus tables
  src/backend/distributed/commands/index.c
  src/test/regress/expected/multi_index_statements.out
  src/test/regress/sql/multi_index_statements.sql
Labels: feature

#4419 Do metadata sync in a separate background worker.
  src/backend/distributed/commands/function.c
  src/backend/distributed/metadata/metadata_sync.c
  src/backend/distributed/metadata/node_metadata.c
  src/backend/distributed/test/metadata_sync.c
  src/backend/distributed/transaction/transaction_management.c
  src/backend/distributed/utils/maintenanced.c
  src/include/distributed/maintenanced.h
  src/include/distributed/metadata_sync.h
  src/include/distributed/transaction_management.h
  src/test/regress/expected/isolation_dump_global_wait_edges.out
  src/test/regress/expected/isolation_metadata_sync_deadlock.out
  src/test/regress/expected/multi_mx_node_metadata.out
  src/test/regress/expected/multi_test_helpers_superuser.out
  src/test/regress/isolation_schedule
  src/test/regress/spec/isolation_metadata_sync_deadlock.spec
  src/test/regress/sql/multi_mx_node_metadata.sql
  src/test/regress/sql/multi_test_helpers_superuser.sql
Labels: needs-description

#4449 Fixes the table used in the error message
  src/backend/distributed/commands/table.c
  src/test/regress/expected/multi_partitioning.out
Labels: bug

#4450 Fix fkey graph test for self reference
  src/test/regress/expected/multi_foreign_key_relation_graph.out
  src/test/regress/sql/multi_foreign_key_relation_graph.sql
Labels: regression tests

#4452 Implement GetPgDependTuplesForDependingObjects
  src/backend/distributed/metadata/dependency.c
  src/include/distributed/metadata/dependency.h
Labels: refactor

#4451 Implement ConstraintWithNameIsOfType
  src/backend/distributed/commands/foreign_constraint.c
  src/backend/distributed/commands/table.c
  src/include/distributed/commands.h
Labels: refactor
