Repository citusdata/citus, pull requests merged in 2020-06, with the labels that each got.

#3859 Check the removeType in IsDropCitusStmt
  src/backend/distributed/commands/extension.c
  src/backend/distributed/commands/utility_hook.c
  src/include/distributed/commands.h
Labels: bug

#3886 Coerce types properly for distribution keys when necessary
  src/backend/distributed/commands/call.c
  src/backend/distributed/planner/function_call_delegation.c
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/planner/shard_pruning.c
  src/include/distributed/shard_pruning.h
  src/test/regress/expected/multi_prune_shard_list.out
  src/test/regress/sql/multi_prune_shard_list.sql
Labels: backport

#3654 Modifying ctes in router planner
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/citus_custom_scan.c
  src/backend/distributed/planner/local_plan_cache.c
  src/backend/distributed/planner/multi_logical_planner.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/utils/citus_clauses.c
  src/include/distributed/citus_clauses.h
  src/include/distributed/multi_executor.h
  src/include/distributed/multi_logical_planner.h
  src/test/regress/bin/normalize.sed
  src/test/regress/expected/cte_inline.out
  src/test/regress/expected/cte_inline_0.out
  src/test/regress/expected/fast_path_router_modify.out
  src/test/regress/expected/foreign_key_restriction_enforcement.out
  src/test/regress/expected/insert_select_repartition.out
  src/test/regress/expected/isolation_select_for_update.out
  src/test/regress/expected/isolation_update_vs_all.out
  src/test/regress/expected/multi_router_planner.out
  src/test/regress/expected/multi_router_planner_fast_path.out
  src/test/regress/expected/relation_access_tracking.out
  src/test/regress/expected/with_modifying.out
  src/test/regress/expected/with_prepare.out
  src/test/regress/spec/isolation_select_for_update.spec
  src/test/regress/spec/isolation_update_vs_all.spec
  src/test/regress/sql/foreign_key_restriction_enforcement.sql
  src/test/regress/sql/multi_router_planner.sql
  src/test/regress/sql/relation_access_tracking.sql
  src/test/regress/sql/with_modifying.sql
  src/test/regress/sql/with_prepare.sql
Labels: performance

#3887 Implement local table joins in router planner
  src/backend/distributed/executor/citus_custom_scan.c
  src/backend/distributed/planner/deparse_shard_query.c
  src/backend/distributed/planner/distributed_planner.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/include/distributed/multi_router_planner.h
  src/test/regress/expected/coordinator_shouldhaveshards.out
  src/test/regress/expected/local_shard_copy.out
  src/test/regress/expected/locally_execute_intermediate_results.out
  src/test/regress/expected/multi_modifications.out
  src/test/regress/expected/multi_mx_add_coordinator.out
  src/test/regress/expected/multi_router_planner.out
  src/test/regress/expected/multi_test_helpers.out
  src/test/regress/expected/replicate_reference_tables_to_coordinator.out
  src/test/regress/expected/set_operation_and_local_tables.out
  src/test/regress/expected/with_executors.out
  src/test/regress/sql/coordinator_shouldhaveshards.sql
  src/test/regress/sql/locally_execute_intermediate_results.sql
  src/test/regress/sql/multi_modifications.sql
  src/test/regress/sql/multi_mx_add_coordinator.sql
  src/test/regress/sql/multi_test_helpers.sql
  src/test/regress/sql/replicate_reference_tables_to_coordinator.sql
  src/test/regress/sql/set_operation_and_local_tables.sql
  src/test/regress/sql/with_executors.sql
Labels: sql, technical debt

#3839 Create EnsureTableCanBeCreated for some checks
  src/backend/distributed/commands/create_distributed_table.c
Labels: refactor

#3912 Use rename to make sure no files are inserted while deleting
  src/backend/distributed/executor/intermediate_results.c
Labels: bug

#3942 citus_evaluate_expression: call expand_function_arguments beforehand to avoid segfaulting on implicit parameters
  src/backend/distributed/utils/citus_clauses.c
  src/test/regress/expected/multi_function_evaluation.out
  src/test/regress/sql/multi_function_evaluation.sql
Labels: bug

#3941 Fix/task execution
  src/backend/distributed/executor/multi_task_tracker_executor.c
  src/backend/distributed/executor/repartition_join_execution.c
  src/include/distributed/multi_task_tracker_executor.h
  src/test/regress/expected/chbenchmark_all_queries.out
  src/test/regress/sql/chbenchmark_all_queries.sql
Labels: bug

#3944 test task tracker repartition with replication >1
  src/test/regress/expected/single_hash_repartition_join.out
  src/test/regress/sql/single_hash_repartition_join.sql
Labels: regression tests

#3868 Fix assertion error when rolling back to savepoint
  src/backend/distributed/transaction/remote_transaction.c
  src/backend/distributed/transaction/transaction_management.c
  src/test/regress/expected/rollback_to_savepoint.out
  src/test/regress/multi_schedule
  src/test/regress/multi_schedule_hyperscale
  src/test/regress/sql/rollback_to_savepoint.sql
Labels: backport, bug
