Repository citusdata/citus, pull requests merged in 2020-04, with the labels that each got.

#3636 add local shard creation support
  src/backend/distributed/commands/call.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/distributed_intermediate_results.c
  src/backend/distributed/executor/insert_select_executor.c
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/master/master_stage_protocol.c
  src/backend/distributed/planner/local_plan_cache.c
  src/include/distributed/adaptive_executor.h
  src/include/distributed/local_executor.h
  src/include/distributed/multi_executor.h
  src/test/regress/bin/normalize.sed
  src/test/regress/expected/coordinator_shouldhaveshards.out
  src/test/regress/expected/local_shard_copy.out
  src/test/regress/expected/local_shard_utility_command_execution.out
  src/test/regress/sql/coordinator_shouldhaveshards.sql
  src/test/regress/sql/local_shard_copy.sql
Labels: feature

#3680 Evaluate nextval in the target list on the coordinator
  src/backend/distributed/executor/insert_select_executor.c
  src/backend/distributed/planner/insert_select_planner.c
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/backend/distributed/planner/multi_router_planner.c
  src/test/regress/expected/multi_insert_select.out
  src/test/regress/expected/multi_simple_queries.out
  src/test/regress/expected/multi_simple_queries_0.out
  src/test/regress/sql/multi_insert_select.sql
  src/test/regress/sql/multi_simple_queries.sql
Labels: bug

#3699 fix multi utilities vacuum test
  src/test/regress/expected/multi_utilities.out
  src/test/regress/sql/multi_utilities.sql
Labels: regression tests

#3702 not wait forever in multi_extension test
  src/test/regress/expected/multi_extension.out
  src/test/regress/sql/multi_extension.sql
Labels: regression tests

#3705 fix flaky log statement in null_parameters
  src/test/regress/expected/null_parameters.out
  src/test/regress/sql/null_parameters.sql
Labels: regression tests

#3718 not log in debug level in null parameters
  src/test/regress/expected/null_parameters.out
  src/test/regress/sql/null_parameters.sql
Labels: regression tests

#3711 fix null tupleStoreState case in ExecuteLocalTaskListExtended
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/local_executor.c
  src/test/regress/bin/normalize.sed
  src/test/regress/expected/coordinator_shouldhaveshards.out
  src/test/regress/sql/coordinator_shouldhaveshards.sql
Labels: bug

#3720 Simplify and fix issues in intermediate result pruning
  src/backend/distributed/planner/distributed_planner.c
  src/backend/distributed/planner/intermediate_result_pruning.c
  src/backend/distributed/planner/multi_master_planner.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/utils/citus_copyfuncs.c
  src/backend/distributed/utils/citus_outfuncs.c
  src/include/distributed/intermediate_result_pruning.h
  src/include/distributed/multi_physical_planner.h
  src/test/regress/expected/intermediate_result_pruning.out
  src/test/regress/expected/multi_subquery.out
  src/test/regress/expected/window_functions.out
  src/test/regress/sql/intermediate_result_pruning.sql
  src/test/regress/sql/window_functions.sql
Labels: bug, refactor

#3715 explicitly return false if transaction connected to local node
  src/backend/distributed/commands/multi_copy.c
  src/backend/distributed/executor/local_executor.c
Labels: refactor

#3738 return early in ExecuteTaskListExtended in error case
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/local_executor.c
Labels: refactor

#3737 test that we don't leak intermediate schemas
  src/backend/distributed/executor/repartition_join_execution.c
  src/backend/distributed/transaction/transaction_management.c
  src/test/regress/expected/ensure_no_intermediate_data_leak.out
  src/test/regress/sql/ensure_no_intermediate_data_leak.sql
Labels: bug, regression tests

#3714 use local execution within transaction block
  src/backend/distributed/executor/local_executor.c
  src/test/regress/expected/coordinator_shouldhaveshards.out
  src/test/regress/expected/local_shard_execution.out
  src/test/regress/expected/local_shard_utility_command_execution.out
  src/test/regress/expected/locally_execute_intermediate_results.out
  src/test/regress/expected/multi_mx_truncate_from_worker.out
  src/test/regress/sql/local_shard_execution.sql
Labels: feature

#3730 read database name inside the function
  src/test/regress/expected/multi_extension.out
  src/test/regress/sql/multi_extension.sql
Labels: regression tests

#3697 enable local table join with reference table
  src/backend/distributed/executor/multi_executor.c
  src/test/regress/expected/coordinator_shouldhaveshards.out
  src/test/regress/expected/replicate_reference_tables_to_coordinator.out
  src/test/regress/sql/coordinator_shouldhaveshards.sql
  src/test/regress/sql/replicate_reference_tables_to_coordinator.sql
Labels: feature

#3733 use an enum for local execution status
  src/backend/distributed/commands/local_multi_copy.c
  src/backend/distributed/commands/multi_copy.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/executor/repartition_join_execution.c
  src/backend/distributed/master/master_delete_protocol.c
  src/backend/distributed/planner/local_plan_cache.c
  src/backend/distributed/transaction/transaction_management.c
  src/include/distributed/local_executor.h
Labels: bug, refactor

#3690 Correctly handle non-constant LIMIT/OFFSET clauses
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/backend/distributed/planner/multi_logical_planner.c
  src/test/regress/expected/multi_limit_clause.out
  src/test/regress/sql/multi_limit_clause.sql
Labels: bug

#3693 Refactor CopyLocalDataIntoShards
  src/backend/distributed/commands/create_distributed_table.c
Labels: refactor

#3731 not wait forever in upgrade distributed function before
  src/test/regress/expected/upgrade_distributed_function_before.out
  src/test/regress/sql/upgrade_distributed_function_before.sql
Labels: regression tests

#3740 GetConnParams: Set runtimeParamStart before setting keywords/values to avoid out of bounds access
  src/backend/distributed/connection/connection_configuration.c
  src/backend/distributed/connection/connection_management.c
Labels: bug

#3744 decrease log level in multi router planner fast path test
  src/test/regress/multi_schedule
Labels: regression tests

#3747 add execution params struct
  src/backend/distributed/commands/call.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/distributed_intermediate_results.c
  src/include/distributed/multi_executor.h
Labels: refactor

#3017 Propagate notices from queries as notices
  src/backend/distributed/commands/call.c
  src/backend/distributed/connection/connection_management.c
  src/backend/distributed/connection/worker_log_messages.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/citus_custom_scan.c
  src/backend/distributed/executor/intermediate_results.c
  src/backend/distributed/planner/distributed_planner.c
  src/backend/distributed/shared_library_init.c
  src/backend/distributed/transaction/transaction_management.c
  src/include/distributed/connection_management.h
  src/include/distributed/distributed_planner.h
  src/include/distributed/error_codes.h
  src/include/distributed/log_utils.h
  src/include/distributed/worker_log_messages.h
  src/test/regress/expected/distributed_functions.out
  src/test/regress/expected/intermediate_results.out
  src/test/regress/expected/local_shard_copy.out
  src/test/regress/expected/multi_function_evaluation.out
  src/test/regress/expected/multi_modifying_xacts.out
  src/test/regress/expected/multi_mx_call.out
  src/test/regress/expected/multi_mx_function_call_delegation.out
  src/test/regress/pg_regress_multi.pl
  src/test/regress/sql/distributed_functions.sql
  src/test/regress/sql/intermediate_results.sql
Labels: bug

#3774 introduce TASK_QUERY_NULL task type
  src/backend/distributed/planner/deparse_shard_query.c
  src/include/distributed/multi_physical_planner.h
  src/test/regress/expected/multi_mx_reference_table.out
  src/test/regress/sql/multi_mx_reference_table.sql
Labels: bug

#3757 Avoid setting hasWindowFuncs true after window functions have been optimized out of query
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/test/regress/expected/window_functions.out
  src/test/regress/sql/window_functions.sql
Labels: bug

#3758 invalidate plan cache in master_update_node
  src/backend/distributed/connection/shared_connection_stats.c
  src/backend/distributed/metadata/node_metadata.c
  src/backend/distributed/sql/citus--9.2-4--9.3-2.sql
  src/test/regress/expected/multi_mx_node_metadata.out
  src/test/regress/sql/multi_mx_node_metadata.sql
Labels: bug

#3756 maintenanced: use before_shmem_exit to clear workerPid
  src/backend/distributed/utils/maintenanced.c
Labels: bug

#3784 Add base isolation schedule
  src/test/regress/Makefile
  src/test/regress/base_isolation_schedule
Labels: isolation tests

#3799 Fix COPY TO's COPY (SELECT) with distributed table having generated columns
  src/backend/distributed/commands/multi_copy.c
  src/test/regress/expected/pg12.out
  src/test/regress/sql/pg12.sql
Labels: bug

#3802 Fix task copy and appending empty task in ExtractLocalAndRemoteTasks
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/utils/citus_copyfuncs.c
  src/test/regress/expected/coordinator_shouldhaveshards.out
  src/test/regress/expected/multi_reference_table.out
  src/test/regress/sql/coordinator_shouldhaveshards.sql
  src/test/regress/sql/multi_reference_table.sql
Labels: bug
