Repository citusdata/citus, pull requests merged in 2020-01, with the labels that each got.

#3306 Fix union (all) pushdown issue
  src/backend/distributed/planner/query_pushdown_planning.c
  src/backend/distributed/planner/relation_restriction_equivalence.c
  src/test/regress/expected/ch_bench_having.out
  src/test/regress/expected/ch_bench_having_mx.out
  src/test/regress/expected/ch_bench_subquery_repartition.out
  src/test/regress/expected/dml_recursive.out
  src/test/regress/expected/full_join.out
  src/test/regress/expected/multi_dropped_column_aliases.out
  src/test/regress/expected/multi_shard_modify.out
  src/test/regress/expected/multi_shard_update_delete.out
  src/test/regress/expected/multi_subquery.out
  src/test/regress/expected/multi_subquery_behavioral_analytics.out
  src/test/regress/expected/multi_subquery_complex_queries.out
  src/test/regress/expected/multi_subquery_complex_reference_clause.out
  src/test/regress/expected/multi_subquery_in_where_clause.out
  src/test/regress/expected/multi_subquery_union.out
  src/test/regress/expected/non_colocated_subquery_joins.out
  src/test/regress/expected/set_operations.out
  src/test/regress/output/multi_outer_join.source
  src/test/regress/output/multi_outer_join_reference.source
  src/test/regress/sql/set_operations.sql
Labels: bug

#3333 Make sure to update shard states of partitions on failures
  src/backend/distributed/connection/placement_connection.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/master/master_metadata_utility.c
  src/include/distributed/master_metadata_utility.h
  src/test/regress/expected/failure_replicated_partitions.out
  src/test/regress/failure_schedule
  src/test/regress/sql/failure_replicated_partitions.sql
Labels: bug

#3364 Refactor deparsing/planning to use DistributeObjectOps struct
  src/backend/distributed/commands/cluster.c
  src/backend/distributed/commands/collation.c
  src/backend/distributed/commands/create_distributed_table.c
  src/backend/distributed/commands/dependencies.c
  src/backend/distributed/commands/distribute_object_ops.c
  src/backend/distributed/commands/extension.c
  src/backend/distributed/commands/function.c
  src/backend/distributed/commands/grant.c
  src/backend/distributed/commands/index.c
  src/backend/distributed/commands/policy.c
  src/backend/distributed/commands/rename.c
  src/backend/distributed/commands/role.c
  src/backend/distributed/commands/schema.c
  src/backend/distributed/commands/table.c
  src/backend/distributed/commands/truncate.c
  src/backend/distributed/commands/type.c
  src/backend/distributed/commands/utility_hook.c
  src/backend/distributed/commands/vacuum.c
  src/backend/distributed/commands/variableset.c
  src/backend/distributed/connection/connection_management.c
  src/backend/distributed/deparser/deparse.c
  src/backend/distributed/deparser/deparse_attribute_stmts.c
  src/backend/distributed/deparser/deparse_collation_stmts.c
  src/backend/distributed/deparser/deparse_extension_stmts.c
  src/backend/distributed/deparser/deparse_function_stmts.c
  src/backend/distributed/deparser/deparse_role_stmts.c
  src/backend/distributed/deparser/deparse_type_stmts.c
  src/backend/distributed/deparser/objectaddress.c
  src/backend/distributed/deparser/qualify.c
  src/backend/distributed/deparser/qualify_collation_stmt.c
  src/backend/distributed/deparser/qualify_function_stmt.c
  src/backend/distributed/deparser/qualify_type_stmt.c
  src/backend/distributed/master/master_create_shards.c
  src/backend/distributed/master/master_stage_protocol.c
  src/backend/distributed/metadata/dependency.c
  src/backend/distributed/metadata/metadata_sync.c
  src/backend/distributed/transaction/worker_transaction.c
  src/backend/distributed/utils/foreign_key_relationship.c
  src/backend/distributed/worker/worker_create_or_replace.c
  src/backend/distributed/worker/worker_partition_protocol.c
  src/include/distributed/commands.h
  src/include/distributed/connection_management.h
  src/include/distributed/deparser.h
  src/include/distributed/errormessage.h
  src/include/distributed/master_metadata_utility.h
  src/include/distributed/shardinterval_utils.h
  src/include/distributed/worker_transaction.h
Labels: refactor

#3371 Fix row-gather for subqueries being handled by task-tracker
  src/backend/distributed/planner/multi_physical_planner.c
  src/test/regress/expected/aggregate_support.out
  src/test/regress/sql/aggregate_support.sql
Labels: bug

#3372 Replace ARRAY_OUT_FUNC_ID with postgres's F_ARRAY_OUT
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/include/distributed/multi_physical_planner.h
Labels: refactor

#3261 Remove copy from worker for append-partitioned table
  src/backend/distributed/commands/multi_copy.c
  src/include/distributed/master_protocol.h
  src/test/regress/input/multi_copy.source
  src/test/regress/output/multi_copy.source
Labels: technical debt

#3369 Defer shard pruning for fast-path router queries to execution
  src/backend/distributed/executor/citus_custom_scan.c
  src/backend/distributed/planner/distributed_planner.c
  src/backend/distributed/planner/fast_path_router_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/utils/citus_copyfuncs.c
  src/include/distributed/distributed_planner.h
  src/include/distributed/multi_router_planner.h
  src/test/regress/expected/fast_path_router_modify.out
  src/test/regress/expected/multi_prune_shard_list.out
  src/test/regress/expected/multi_router_planner_fast_path.out
  src/test/regress/expected/multi_sql_function.out
  src/test/regress/expected/multi_utility_statements.out
  src/test/regress/sql/fast_path_router_modify.sql
  src/test/regress/sql/multi_prune_shard_list.sql
  src/test/regress/sql/multi_sql_function.sql
  src/test/regress/sql/multi_utility_statements.sql
Labels: performance

#3350 Lazy query deparsing executable queries
  src/backend/distributed/commands/call.c
  src/backend/distributed/commands/index.c
  src/backend/distributed/commands/table.c
  src/backend/distributed/commands/utility_hook.c
  src/backend/distributed/commands/vacuum.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/distributed_intermediate_results.c
  src/backend/distributed/executor/insert_select_executor.c
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/executor/multi_task_tracker_executor.c
  src/backend/distributed/master/master_stage_protocol.c
  src/backend/distributed/master/master_truncate.c
  src/backend/distributed/planner/deparse_shard_query.c
  src/backend/distributed/planner/distributed_planner.c
  src/backend/distributed/planner/function_call_delegation.c
  src/backend/distributed/planner/multi_explain.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/utils/citus_copyfuncs.c
  src/backend/distributed/utils/citus_outfuncs.c
  src/backend/distributed/utils/citus_readfuncs.c
  src/include/distributed/deparse_shard_query.h
  src/include/distributed/local_executor.h
  src/include/distributed/multi_physical_planner.h
  src/test/regress/expected/coordinator_shouldhaveshards.out
  src/test/regress/expected/local_shard_execution.out
  src/test/regress/expected/multi_reference_table.out
  src/test/regress/sql/coordinator_shouldhaveshards.sql
  src/test/regress/sql/local_shard_execution.sql
  src/test/regress/sql/multi_reference_table.sql
Labels: performance

#3428 switch back to old memory context in cache local plan for task
  src/backend/distributed/executor/citus_custom_scan.c
Labels: bug
