Repository citusdata/citus, pull requests merged in 2020-03, with the labels that each got.

#3562 For composite types, add cast to the parameter to ease remote node detect the type
  src/backend/distributed/deparser/ruleutils_11.c
  src/backend/distributed/deparser/ruleutils_12.c
  src/test/regress/expected/multi_data_types.out
  src/test/regress/expected/multi_prepare_sql.out
  src/test/regress/sql/multi_data_types.sql
  src/test/regress/sql/multi_prepare_sql.sql
Labels: backport

#3553 Refactor CitusBeginScan into separate SELECT / DML paths
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/citus_custom_scan.c
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/planner/deparse_shard_query.c
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/utils/citus_clauses.c
  src/backend/distributed/utils/citus_copyfuncs.c
  src/backend/distributed/utils/citus_outfuncs.c
  src/include/distributed/deparse_shard_query.h
  src/include/distributed/multi_physical_planner.h
  src/include/distributed/multi_router_planner.h
  src/test/regress/expected/local_shard_execution.out
  src/test/regress/expected/master_evaluation.out
  src/test/regress/expected/master_evaluation_modify.out
  src/test/regress/expected/master_evaluation_select.out
  src/test/regress/multi_mx_schedule
  src/test/regress/sql/local_shard_execution.sql
  src/test/regress/sql/master_evaluation.sql
  src/test/regress/sql/master_evaluation_modify.sql
  src/test/regress/sql/master_evaluation_select.sql
Labels: backport, bug

#3564 Fix early exits on intermediate result pruning
  src/backend/distributed/planner/intermediate_result_pruning.c
  src/test/regress/expected/intermediate_result_pruning.out
  src/test/regress/expected/local_shard_execution.out
  src/test/regress/expected/multi_read_from_secondaries.out
  src/test/regress/sql/intermediate_result_pruning.sql
  src/test/regress/sql/local_shard_execution.sql
  src/test/regress/sql/multi_read_from_secondaries.sql
Labels: backport, bug

#3571 refactor CoordinatedTransactionCallback
  src/backend/distributed/transaction/transaction_management.c
Labels: refactor

#3593 Create a macro SLOW_START_DISABLED
  src/backend/distributed/executor/adaptive_executor.c
Labels: refactor

#3596 add a utility to get shard oid from relation oid and shard id
  src/backend/distributed/planner/deparse_shard_query.c
  src/backend/distributed/utils/shard_utils.c
  src/include/distributed/shard_utils.h
Labels: refactor

#3578 Improve definition of RelationInfoContainsOnlyRecurringTuples
  src/backend/distributed/planner/query_pushdown_planning.c
  src/test/regress/expected/with_basics.out
  src/test/regress/sql/with_basics.sql
Labels: backport, bug

#3568 First phase of addressing HAVING subquery issues
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/backend/distributed/planner/multi_logical_planner.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/planner/recursive_planning.c
  src/include/distributed/multi_logical_planner.h
  src/test/regress/bin/normalize.sed
  src/test/regress/expected/ch_bench_having.out
  src/test/regress/expected/ch_bench_having_mx.out
  src/test/regress/expected/multi_reference_table.out
  src/test/regress/expected/multi_select_distinct.out
  src/test/regress/expected/multi_subquery.out
  src/test/regress/sql/multi_reference_table.sql
  src/test/regress/sql/multi_select_distinct.sql
  src/test/regress/sql/multi_subquery.sql
Labels: backport, bug

#3584 Simplify INSERT logic in router planner
  src/backend/distributed/executor/citus_custom_scan.c
  src/backend/distributed/planner/multi_router_planner.c
  src/test/regress/expected/multi_router_planner.out
  src/test/regress/expected/multi_router_planner_fast_path.out
Labels: technical debt

#3608 Also check aggregates in havingQual when scanning for non pushdownable aggregates
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/test/regress/expected/multi_subquery.out
  src/test/regress/sql/multi_subquery.sql
Labels: backport, bug

#3600 Add runtime type checking to AGGREGATE_CUSTOM_COMBINE helper functions
  src/backend/distributed/utils/aggregate_utils.c
  src/test/regress/expected/aggregate_support.out
  src/test/regress/sql/aggregate_support.sql
Labels: backport, bug

#3623 add update_distributed_table_colocation UDF to update colocation for table
  src/backend/distributed/commands/create_distributed_table.c
  src/backend/distributed/master/master_metadata_utility.c
  src/backend/distributed/sql/citus--9.2-2--9.3-1.sql
  src/backend/distributed/sql/udfs/update_distributed_table_colocation/9.3-1.sql
  src/backend/distributed/sql/udfs/update_distributed_table_colocation/latest.sql
  src/backend/distributed/utils/colocation_utils.c
  src/include/distributed/colocation_utils.h
  src/include/distributed/master_metadata_utility.h
  src/test/regress/expected/multi_colocation_utils.out
  src/test/regress/sql/multi_colocation_utils.sql
Labels: feature

#3640 not run local shard copy test in parallel
  src/test/regress/multi_mx_schedule
Labels: regression tests

#3653 Don't segfault on queries using GROUPING
  src/backend/distributed/planner/extended_op_node_utils.c
  src/backend/distributed/planner/multi_logical_planner.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/test/regress/expected/aggregate_support.out
  src/test/regress/sql/aggregate_support.sql
Labels: backport, bug

#3649 store query command list in task
  src/backend/distributed/commands/utility_hook.c
  src/backend/distributed/master/master_stage_protocol.c
  src/backend/distributed/planner/deparse_shard_query.c
  src/backend/distributed/utils/citus_copyfuncs.c
  src/backend/distributed/utils/citus_outfuncs.c
  src/include/distributed/deparse_shard_query.h
  src/include/distributed/multi_physical_planner.h
Labels: refactor

#3651 Fix a bug which caused queries with SRFs and function evaluation to fail
  src/backend/distributed/utils/citus_clauses.c
  src/test/regress/expected/multi_function_evaluation.out
  src/test/regress/sql/multi_function_evaluation.sql
Labels: bug

#3672 not append the delimiter to the end in StringJoin
  src/backend/distributed/utils/listutils.c
Labels: refactor

#3667 extract local plan cache related methods into a file
  src/backend/distributed/executor/citus_custom_scan.c
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/planner/local_plan_cache.c
  src/include/distributed/citus_custom_scan.h
  src/include/distributed/local_plan_cache.h
Labels: refactor

#3668 Fix error when using LEFT JOIN with GROUP BY on primary key
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/planner/query_pushdown_planning.c
  src/include/distributed/multi_physical_planner.h
  src/test/regress/expected/subquery_complex_target_list.out
  src/test/regress/sql/subquery_complex_target_list.sql
Labels: bug

#3659 refactor query string of task
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/distributed_intermediate_results.c
  src/backend/distributed/executor/insert_select_executor.c
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/executor/multi_task_tracker_executor.c
  src/backend/distributed/master/master_delete_protocol.c
  src/backend/distributed/planner/deparse_shard_query.c
  src/backend/distributed/planner/function_call_delegation.c
  src/backend/distributed/planner/multi_explain.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/utils/citus_copyfuncs.c
  src/backend/distributed/utils/citus_outfuncs.c
  src/include/distributed/citus_nodefuncs.h
  src/include/distributed/deparse_shard_query.h
  src/include/distributed/multi_physical_planner.h
Labels: refactor

#3681 decrease cirleci no output timeout to 2 mins from 10 mins
  .circleci/config.yml
Labels: regression tests

#3617 refactor ExecuteLocalTaskList
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/local_executor.c
  src/include/distributed/local_executor.h
Labels: refactor

#3682 disable one permutation in deadlock detection isolation test
  src/test/regress/expected/isolation_distributed_deadlock_detection.out
  src/test/regress/expected/isolation_replicate_reference_tables_to_coordinator.out
  src/test/regress/spec/isolation_distributed_deadlock_detection.spec
Labels: regression tests

#3679 Allow table type to be used in target list
  src/backend/distributed/deparser/ruleutils_11.c
  src/backend/distributed/deparser/ruleutils_12.c
  src/test/regress/expected/aggregate_support.out
  src/test/regress/expected/subquery_complex_target_list.out
  src/test/regress/sql/subquery_complex_target_list.sql
Labels: bug
