Repository citusdata/citus, pull requests merged in 2020-02, with the labels that each got.

#3473 Fix: Unnecessary repartition on joins with more than 4 tables
  src/backend/distributed/planner/multi_join_order.c
  src/backend/distributed/planner/multi_logical_planner.c
  src/include/distributed/multi_join_order.h
  src/test/regress/expected/chbenchmark_all_queries.out
  src/test/regress/expected/multi_join_order_additional.out
  src/test/regress/sql/chbenchmark_all_queries.sql
  src/test/regress/sql/multi_join_order_additional.sql
Labels: backport

#3499 enhance local executor description
  src/backend/distributed/executor/local_executor.c
Labels: documentation

#3500 remove unnecessary if check
  src/backend/distributed/executor/local_executor.c
Labels: refactor

#3491 refactor RunDistributedExecution
  src/backend/distributed/executor/adaptive_executor.c
Labels: refactor

#3539 Make merge tables during re-partitioning unlogged
  src/backend/distributed/worker/worker_merge_protocol.c
Labels: backport, performance

#3485 send repartition cleanup jobs in parallel to all workers
  src/backend/distributed/executor/repartition_join_execution.c
  src/backend/distributed/transaction/worker_transaction.c
  src/include/distributed/worker_transaction.h
Labels: backport, performance

#3550 Fix create_distributed_table on a table using GENERATED ALWAYS AS
  src/backend/distributed/commands/multi_copy.c
  src/test/regress/expected/pg12.out
  src/test/regress/sql/pg12.sql
Labels: bug
