Repository citusdata/citus, pull requests merged in 2021-05, with the labels that each got.

#4907 Columnnar: metapage changes.
  src/backend/columnar/columnar_debug.c
  src/backend/columnar/columnar_metadata.c
  src/backend/columnar/columnar_reader.c
  src/backend/columnar/columnar_storage.c
  src/backend/columnar/columnar_tableam.c
  src/backend/columnar/columnar_writer.c
  src/backend/columnar/sql/columnar--10.0-3--10.1-1.sql
  src/backend/columnar/sql/downgrades/columnar--10.1-1--10.0-3.sql
  src/backend/columnar/sql/udfs/downgrade_columnar_storage/10.1-1.sql
  src/backend/columnar/sql/udfs/downgrade_columnar_storage/latest.sql
  src/backend/columnar/sql/udfs/upgrade_columnar_storage/10.1-1.sql
  src/backend/columnar/sql/udfs/upgrade_columnar_storage/latest.sql
  src/backend/distributed/transaction/lock_graph.c
  src/include/columnar/columnar.h
  src/include/columnar/columnar_metadata.h
  src/include/columnar/columnar_storage.h
  src/include/distributed/resource_lock.h
  src/test/regress/after_citus_upgrade_coord_schedule
  src/test/regress/before_citus_upgrade_coord_schedule
  src/test/regress/expected/columnar_alter.out
  src/test/regress/expected/columnar_create.out
  src/test/regress/expected/columnar_empty.out
  src/test/regress/expected/columnar_insert.out
  src/test/regress/expected/columnar_rollback.out
  src/test/regress/expected/columnar_test_helpers.out
  src/test/regress/expected/columnar_truncate.out
  src/test/regress/expected/columnar_vacuum.out
  src/test/regress/expected/multi_extension.out
  src/test/regress/expected/upgrade_columnar_metapage_after.out
  src/test/regress/expected/upgrade_columnar_metapage_after_0.out
  src/test/regress/expected/upgrade_columnar_metapage_before.out
  src/test/regress/expected/upgrade_columnar_metapage_before_0.out
  src/test/regress/expected/upgrade_list_citus_objects.out
  src/test/regress/expected/upgrade_list_citus_objects_0.out
  src/test/regress/input/columnar_load.source
  src/test/regress/output/columnar_load.source
  src/test/regress/sql/columnar_alter.sql
  src/test/regress/sql/columnar_create.sql
  src/test/regress/sql/columnar_empty.sql
  src/test/regress/sql/columnar_insert.sql
  src/test/regress/sql/columnar_rollback.sql
  src/test/regress/sql/columnar_test_helpers.sql
  src/test/regress/sql/columnar_truncate.sql
  src/test/regress/sql/columnar_vacuum.sql
  src/test/regress/sql/upgrade_columnar_metapage_after.sql
  src/test/regress/sql/upgrade_columnar_metapage_before.sql
Labels: columnar

#4956 Handle old versioned columnar metapage after binary upgrade
  src/backend/columnar/columnar_storage.c
  src/backend/columnar/columnar_tableam.c
  src/backend/columnar/sql/downgrades/columnar--10.1-1--10.0-3.sql
Labels: columnar

#4967 Close connection after each shard move
  src/backend/distributed/operations/shard_rebalancer.c
Labels: bug

#4965 Implement an helper to create memory cxt for stripe read
  src/backend/columnar/columnar_reader.c
Labels: columnar, refactor

#4964 Move the logic that builds relation col list into a function
  src/backend/columnar/columnar_tableam.c
Labels: columnar, refactor

#4972 Not block maintenance daemon
  src/backend/distributed/operations/shard_cleaner.c
  src/backend/distributed/test/shard_rebalancer.c
  src/backend/distributed/utils/maintenanced.c
  src/include/distributed/shard_cleaner.h
  src/test/regress/expected/isolation_rebalancer_deferred_drop.out
  src/test/regress/spec/isolation_rebalancer_deferred_drop.spec
Labels: bug

#4976 Lookup hostname before execution
  src/backend/distributed/executor/adaptive_executor.c
  src/test/regress/expected/isolation_dump_global_wait_edges.out
  src/test/regress/expected/isolation_update_node.out
  src/test/regress/expected/isolation_update_node_lock_writes.out
  src/test/regress/spec/isolation_update_node.spec
Labels: bug

#4997 Use 2PC when using a node connection
  src/backend/distributed/connection/placement_connection.c
  src/test/regress/expected/multi_transaction_recovery.out
  src/test/regress/sql/multi_transaction_recovery.sql
Labels: backport, bug

#4995 Rename CoordinatedTransactionShouldUse2PC
  src/backend/distributed/commands/multi_copy.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/operations/delete_protocol.c
  src/backend/distributed/transaction/transaction_management.c
  src/backend/distributed/transaction/worker_transaction.c
  src/include/distributed/transaction_management.h
Labels: refactor

#4960 Not consider old placements when disabling or removing a node
  src/backend/distributed/metadata/metadata_utility.c
  src/backend/distributed/metadata/node_metadata.c
  src/include/distributed/metadata_utility.h
  src/test/regress/expected/multi_cluster_management.out
  src/test/regress/sql/multi_cluster_management.sql
Labels: backport, cherry-pick-10.0
