Repository citusdata/citus, pull requests merged in 2021-06, with the labels that each got.

#5029 Enforce table opt constraints when using alter_columnar_table_set
  src/backend/columnar/columnar_tableam.c
  src/test/regress/expected/columnar_citus_integration.out
  src/test/regress/expected/columnar_empty.out
  src/test/regress/expected/columnar_insert.out
  src/test/regress/expected/columnar_tableoptions.out
  src/test/regress/expected/multi_multiuser.out
  src/test/regress/sql/columnar_citus_integration.sql
  src/test/regress/sql/columnar_empty.sql
  src/test/regress/sql/columnar_insert.sql
  src/test/regress/sql/columnar_tableoptions.sql
  src/test/regress/sql/multi_multiuser.sql
Labels: backport, columnar

#5046 Fix nextval('seq_name'::text) bug, and schema for seq tests
  src/backend/distributed/deparser/citus_ruleutils.c
  src/test/regress/expected/multi_sequence_default.out
  src/test/regress/sql/multi_sequence_default.sql
Labels: cherry-pick-10.1

#5048 Fix a bug that causes worker_create_or_alter_role to crash with NULL input
  src/backend/distributed/utils/role.c
  src/test/regress/expected/multi_utilities.out
  src/test/regress/sql/multi_utilities.sql
Labels: cherry-pick-10.1

#5025 Split multi schedule
  .circleci/config.yml
  src/test/regress/Makefile
  src/test/regress/expected/multi_modifying_xacts.out
  src/test/regress/multi_1_schedule
  src/test/regress/multi_schedule
  src/test/regress/sql/multi_modifying_xacts.sql
Labels: regression tests

#5049 Set table size to zero if no size is read
  src/backend/distributed/metadata/metadata_utility.c
Labels: cherry-pick-10.1

#4950 Add basic index support for columnar tables
  src/backend/columnar/columnar_customscan.c
  src/backend/columnar/columnar_metadata.c
  src/backend/columnar/columnar_reader.c
  src/backend/columnar/columnar_storage.c
  src/backend/columnar/columnar_tableam.c
  src/backend/distributed/commands/index.c
  src/include/columnar/columnar.h
  src/include/distributed/commands.h
  src/test/regress/expected/columnar_alter.out
  src/test/regress/expected/columnar_create.out
  src/test/regress/expected/columnar_indexes.out
  src/test/regress/sql/columnar_alter.sql
  src/test/regress/sql/columnar_create.sql
  src/test/regress/sql/columnar_indexes.sql
Labels: columnar

#5052 Merge columnar metapage changes and basic index support
  src/backend/columnar/columnar_customscan.c
  src/backend/columnar/columnar_debug.c
  src/backend/columnar/columnar_metadata.c
  src/backend/columnar/columnar_reader.c
  src/backend/columnar/columnar_storage.c
  src/backend/columnar/columnar_tableam.c
  src/backend/columnar/columnar_writer.c
  src/backend/columnar/sql/columnar--10.1-1--10.2-1.sql
  src/backend/columnar/sql/downgrades/columnar--10.2-1--10.1-1.sql
  src/backend/columnar/sql/udfs/downgrade_columnar_storage/10.2-1.sql
  src/backend/columnar/sql/udfs/downgrade_columnar_storage/latest.sql
  src/backend/columnar/sql/udfs/upgrade_columnar_storage/10.2-1.sql
  src/backend/columnar/sql/udfs/upgrade_columnar_storage/latest.sql
  src/backend/distributed/commands/index.c
  src/backend/distributed/sql/citus--10.1-1--10.2-1.sql
  src/backend/distributed/sql/downgrades/citus--10.2-1--10.1-1.sql
  src/backend/distributed/transaction/lock_graph.c
  src/include/columnar/columnar.h
  src/include/columnar/columnar_metadata.h
  src/include/columnar/columnar_storage.h
  src/include/columnar/columnar_tableam.h
  src/include/distributed/commands.h
  src/include/distributed/resource_lock.h
  src/test/regress/after_citus_upgrade_coord_schedule
  src/test/regress/before_citus_upgrade_coord_schedule
  src/test/regress/columnar_schedule
  src/test/regress/expected/columnar_alter.out
  src/test/regress/expected/columnar_create.out
  src/test/regress/expected/columnar_empty.out
  src/test/regress/expected/columnar_first_row_number.out
  src/test/regress/expected/columnar_indexes.out
  src/test/regress/expected/columnar_insert.out
  src/test/regress/expected/columnar_rollback.out
  src/test/regress/expected/columnar_test_helpers.out
  src/test/regress/expected/columnar_truncate.out
  src/test/regress/expected/columnar_vacuum.out
  src/test/regress/expected/columnar_write_concurrency.out
  src/test/regress/expected/multi_extension.out
  src/test/regress/expected/multi_multiuser.out
  src/test/regress/expected/upgrade_columnar_metapage_after.out
  src/test/regress/expected/upgrade_columnar_metapage_after_0.out
  src/test/regress/expected/upgrade_columnar_metapage_before.out
  src/test/regress/expected/upgrade_columnar_metapage_before_0.out
  src/test/regress/expected/upgrade_list_citus_objects.out
  src/test/regress/expected/upgrade_list_citus_objects_0.out
  src/test/regress/input/columnar_load.source
  src/test/regress/output/columnar_load.source
  src/test/regress/spec/columnar_write_concurrency.spec
  src/test/regress/sql/columnar_alter.sql
  src/test/regress/sql/columnar_create.sql
  src/test/regress/sql/columnar_empty.sql
  src/test/regress/sql/columnar_first_row_number.sql
  src/test/regress/sql/columnar_indexes.sql
  src/test/regress/sql/columnar_insert.sql
  src/test/regress/sql/columnar_rollback.sql
  src/test/regress/sql/columnar_test_helpers.sql
  src/test/regress/sql/columnar_truncate.sql
  src/test/regress/sql/columnar_vacuum.sql
  src/test/regress/sql/upgrade_columnar_metapage_after.sql
  src/test/regress/sql/upgrade_columnar_metapage_before.sql
Labels: columnar

#5027 Use correct test schedule name in check-columnar-vg
  src/test/regress/Makefile
Labels: columnar

#5053 Deparse/parse the local cached queries
  src/backend/distributed/executor/citus_custom_scan.c
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/planner/deparse_shard_query.c
  src/backend/distributed/planner/local_plan_cache.c
  src/include/distributed/deparse_shard_query.h
  src/include/distributed/local_executor.h
  src/include/distributed/local_plan_cache.h
  src/test/regress/expected/local_shard_execution_dropped_column.out
  src/test/regress/multi_mx_schedule
  src/test/regress/sql/local_shard_execution_dropped_column.sql
Labels: cherry-pick-10.1

#5050 Avoid two race conditions in the rebalance progress monitor
  src/backend/distributed/operations/shard_rebalancer.c
  src/backend/distributed/progress/multi_progress.c
  src/backend/distributed/test/progress_utils.c
  src/include/distributed/multi_progress.h
Labels: cherry-pick-10.1

#5066 fix regression tests to avoid any conflicts in enterprise
  src/test/regress/expected/local_shard_execution_dropped_column.out
  src/test/regress/sql/local_shard_execution_dropped_column.sql
Labels: cherry-pick-10.1

#5072 Only allow moves of shards of distributed tables
  src/backend/distributed/operations/repair_shards.c
  src/backend/distributed/operations/shard_rebalancer.c
  src/include/distributed/coordinator_protocol.h
  src/include/distributed/repair_shards.h
  src/test/regress/expected/shard_rebalancer.out
  src/test/regress/sql/shard_rebalancer.sql
Labels: bug, cherry-pick-10.1

#5071 Harden ReplicateShardToNode to unexpected placements
  src/backend/distributed/utils/reference_table_utils.c
Labels: cleanup, refactor

#5073 Fix check to always allow foreign keys to reference tables
  src/backend/distributed/commands/foreign_constraint.c
  src/test/regress/expected/foreign_key_to_reference_table.out
Labels: bug, cherry-pick-10.1

#4994 Exclude orphaned shards while finding shard placements
  src/backend/distributed/commands/multi_copy.c
  src/backend/distributed/connection/locally_reserved_shared_connections.c
  src/backend/distributed/executor/placement_access.c
  src/backend/distributed/metadata/metadata_cache.c
  src/backend/distributed/metadata/metadata_utility.c
  src/backend/distributed/operations/create_shards.c
  src/backend/distributed/operations/delete_protocol.c
  src/backend/distributed/operations/repair_shards.c
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/test/distribution_metadata.c
  src/backend/distributed/utils/colocation_utils.c
  src/backend/distributed/utils/reference_table_utils.c
  src/backend/distributed/utils/shardinterval_utils.c
  src/backend/distributed/worker/worker_drop_protocol.c
  src/include/distributed/metadata_cache.h
  src/include/distributed/metadata_utility.h
  src/test/regress/expected/ignoring_orphaned_shards.out
  src/test/regress/operations_schedule
  src/test/regress/sql/ignoring_orphaned_shards.sql
Labels: bug, cherry-pick-10.1
