Repository citusdata/citus, pull requests merged in 2021-11, with the labels that each got.

#5435 Fixes ALTER STATISTICS IF EXISTS bug
  src/backend/distributed/commands/statistics.c
  src/test/regress/expected/pg13_propagate_statistics.out
  src/test/regress/sql/pg13_propagate_statistics.sql
Labels: bug

#5436 Fix missing from clause entry
  src/backend/distributed/planner/deparse_shard_query.c
  src/backend/distributed/planner/local_plan_cache.c
  src/include/distributed/deparse_shard_query.h
  src/test/regress/expected/distributed_planning.out
  src/test/regress/expected/distributed_planning_create_load.out
  src/test/regress/sql/distributed_planning.sql
  src/test/regress/sql/distributed_planning_create_load.sql
Labels: bug, backport

#5418 Reinstate optimisation for uniform shard interval ranges
  src/backend/distributed/utils/shardinterval_utils.c
Labels: backport, cherry-pick-10.0, cherry-pick-10.1, cherry-pick-10.2, cherry-pick-9.5

#5441 Allow lock_shard_resources to be called by the users with privileges
  src/backend/distributed/utils/resource_lock.c
  src/test/regress/expected/mx_regular_user.out
  src/test/regress/sql/mx_regular_user.sql
Labels: backport, cherry-pick-10.2

#5458 Skip deleting options if columnar.options is already dropped
  src/backend/columnar/columnar_metadata.c
  src/test/regress/after_pg_upgrade_schedule
  src/test/regress/expected/upgrade_columnar_after.out
  src/test/regress/sql/upgrade_columnar_after.sql
Labels: columnar, cherry-pick-10.0, cherry-pick-10.1, cherry-pick-10.2

#5484 Allow overwriting columnar storage pages written by aborted xacts
  src/backend/columnar/columnar_storage.c
  src/test/regress/expected/columnar_insert.out
  src/test/regress/sql/columnar_insert.sql
Labels: columnar, cherry-pick-10.2, dev_reported
