Repository citusdata/citus, pull requests merged in 2021-03, with the labels that each got.

#4759 Normalize the ConvertTable notices
  src/backend/distributed/commands/alter_table.c
  src/test/regress/expected/alter_distributed_table.out
  src/test/regress/expected/alter_distributed_table_0.out
  src/test/regress/expected/alter_table_set_access_method.out
  src/test/regress/expected/citus_local_tables.out
  src/test/regress/expected/columnar_citus_integration.out
  src/test/regress/expected/columnar_partitioning.out
  src/test/regress/expected/columnar_partitioning_1.out
  src/test/regress/expected/coordinator_shouldhaveshards.out
  src/test/regress/expected/distributed_collations.out
  src/test/regress/expected/multi_mx_alter_distributed_table.out
  src/test/regress/expected/pg12.out
  src/test/regress/expected/pg13_with_ties.out
  src/test/regress/expected/single_node.out
  src/test/regress/expected/undistribute_table.out
Labels: cherry-pick-10.0

#4760 Add security flags in configure scripts
  Makefile.global.in
  configure
  configure.in
Labels: cherry-pick-10.0

#4752 Reimplement citus_update_table_statistics to detect dist. deadlocks
  src/backend/distributed/metadata/metadata_utility.c
  src/backend/distributed/operations/stage_protocol.c
  src/backend/distributed/sql/citus--8.0-1.sql
  src/backend/distributed/sql/udfs/citus_update_table_statistics/10.0-1.sql
  src/backend/distributed/sql/udfs/citus_update_table_statistics/latest.sql
  src/backend/distributed/utils/foreign_key_relationship.c
  src/include/distributed/foreign_key_relationship.h
  src/include/distributed/metadata_utility.h
  src/test/regress/expected/citus_update_table_statistics.out
  src/test/regress/multi_schedule
  src/test/regress/sql/citus_update_table_statistics.sql
Labels: cherry-pick-10.0

#4770 Do not use security flags by default
  configure
  configure.in
Labels: cherry-pick-10.0

#4756 Prevent infinite recursion for queries that involve UNION ALL and JOIN
  src/backend/distributed/planner/distributed_planner.c
  src/backend/distributed/planner/relation_restriction_equivalence.c
  src/include/distributed/distributed_planner.h
  src/test/regress/expected/multi_test_helpers.out
  src/test/regress/expected/set_operations.out
  src/test/regress/expected/union_pushdown.out
  src/test/regress/sql/multi_test_helpers.sql
  src/test/regress/sql/union_pushdown.sql
Labels: bug, cherry-pick-10.0

#4769 Populate DATABASEOID cache before CREATE INDEX CONCURRENTLY
  src/backend/distributed/commands/utility_hook.c
Labels: cherry-pick-10.0

#4767 Try to return earlier in idempotent citus_add_node
  src/backend/distributed/metadata/node_metadata.c
Labels: cherry-pick-10.0

#4765 Fix chunk_group_consistency regression test view
  src/test/regress/expected/columnar_create.out
  src/test/regress/sql/columnar_create.sql
Labels: columnar

#4345 Modernize Citus readme
  README.md
  citus-architecture.png
  citus-readme-banner.png
  citus-scale-out.png
  github-banner.png
Labels: cherry-pick-10.0

#4796 Ignore columnar generated test files
  src/test/regress/expected/.gitignore
  src/test/regress/sql/.gitignore
Labels: regression tests

#4800 Fixes a crash in queries with a modifying CTE and a SELECT without FROM
  src/backend/distributed/planner/deparse_shard_query.c
  src/test/regress/expected/multi_mx_router_planner.out
  src/test/regress/expected/multi_router_planner.out
  src/test/regress/sql/multi_mx_router_planner.sql
  src/test/regress/sql/multi_router_planner.sql
Labels: cherry-pick-10.0

#4587 Skip 2PC for readonly connections in a transaction
  src/backend/distributed/transaction/remote_transaction.c
  src/test/regress/expected/multi_transaction_recovery.out
  src/test/regress/sql/multi_transaction_recovery.sql
Labels: cherry-pick-10.0

#4791 Remove foreign keys between columnar metadata tables
  src/backend/columnar/columnar_metadata_tables.c
  src/backend/columnar/sql/columnar--10.0-3--10.1-1.sql
  src/backend/columnar/sql/downgrades/columnar--10.1-1--10.0-3.sql
  src/backend/distributed/sql/citus--10.0-3--10.1-1.sql
  src/backend/distributed/sql/downgrades/citus--10.1-1--10.0-3.sql
  src/test/regress/expected/columnar_create.out
  src/test/regress/sql/columnar_create.sql
Labels: columnar

#4806 Do not trigger 2PC for reads on local execution
  src/backend/distributed/commands/multi_copy.c
  src/backend/distributed/executor/adaptive_executor.c
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/operations/delete_protocol.c
  src/backend/distributed/test/xact_stats.c
  src/backend/distributed/transaction/transaction_management.c
  src/backend/distributed/transaction/worker_transaction.c
  src/include/distributed/transaction_management.h
  src/test/regress/expected/coordinator_shouldhaveshards.out
  src/test/regress/expected/single_node.out
  src/test/regress/sql/coordinator_shouldhaveshards.sql
  src/test/regress/sql/single_node.sql
Labels: cherry-pick-10.0

#4766 Support temporary columnar tables
  src/backend/columnar/columnar_metadata_tables.c
  src/backend/columnar/columnar_tableam.c
  src/test/regress/columnar_isolation_schedule
  src/test/regress/expected/columnar_create.out
  src/test/regress/expected/columnar_temp_tables.out
  src/test/regress/spec/columnar_temp_tables.spec
  src/test/regress/sql/columnar_create.sql
Labels: columnar

#4817 Remove unnecessary AtEOXact_Files call
  src/backend/distributed/transaction/transaction_management.c
Labels: cherry-pick-10.0

#4814 Columnar: cleanup
  src/backend/columnar/columnar_compression.c
  src/backend/columnar/columnar_customscan.c
  src/backend/columnar/columnar_metadata.c
  src/backend/columnar/columnar_writer.c
  src/include/columnar/columnar.h
  src/include/columnar/columnar_compression.h
  src/include/columnar/columnar_metadata.h
  src/include/columnar/columnar_version_compat.h
  src/include/columnar/mod.h
Labels: columnar

#4808 Add GUC to set maximum connection lifetime
  src/backend/distributed/connection/connection_management.c
  src/backend/distributed/shared_library_init.c
  src/include/distributed/connection_management.h
  src/test/regress/expected/shared_connection_stats.out
  src/test/regress/sql/shared_connection_stats.sql
Labels: cherry-pick-10.0

#4820 Introduce citus.remote_copy_flush_threshold GUC
  src/backend/distributed/connection/remote_commands.c
  src/backend/distributed/shared_library_init.c
  src/include/distributed/remote_commands.h
  src/test/regress/expected/multi_insert_select.out
  src/test/regress/sql/multi_insert_select.sql
Labels: cherry-pick-10.0

#4830 Add udf citus_get_active_worker_nodes
  src/backend/distributed/operations/node_protocol.c
  src/backend/distributed/sql/citus--10.0-2--10.0-3.sql
  src/backend/distributed/sql/downgrades/citus--10.0-3--10.0-2.sql
  src/test/regress/expected/multi_extension.out
  src/test/regress/expected/multi_extension_0.out
  src/test/regress/expected/upgrade_list_citus_objects.out
  src/test/regress/expected/upgrade_list_citus_objects_0.out
  src/test/regress/sql/multi_extension.sql
Labels: cherry-pick-10.0

#4831 Make sure that local execution starts coordinated transaction
  src/backend/distributed/executor/local_executor.c
  src/test/regress/expected/single_node.out
Labels: cherry-pick-10.0

#4825 Remove columnar/.gitignore
  src/backend/columnar/.gitignore
Labels: cleanup, columnar

#4852 Columnar: do not bother building unnecessary RestrictInfo.
  src/backend/columnar/columnar_reader.c
Labels: columnar

#4737 Add check-columnar-vg regression test target
  src/test/regress/Makefile
Labels: columnar
