Repository citusdata/citus, pull requests merged in 2021-01, with the labels that each got.

#4476 Fix flaky test in multi_foreign_key_relation_graph
  src/test/regress/multi_schedule
Labels: regression tests

#4431 Add a view for simple (time) partitions and their access methods
  src/backend/distributed/operations/partitioning.c
  src/backend/distributed/sql/citus--9.5-1--10.0-1.sql
  src/backend/distributed/sql/downgrades/citus--10.0-1--9.5-1.sql
  src/backend/distributed/sql/udfs/time_partition_range/10.0-1.sql
  src/backend/distributed/sql/udfs/time_partition_range/latest.sql
  src/backend/distributed/sql/udfs/time_partitions/10.0-1.sql
  src/backend/distributed/sql/udfs/time_partitions/latest.sql
  src/test/regress/expected/multi_extension.out
  src/test/regress/expected/multi_extension_0.out
  src/test/regress/expected/multi_partitioning.out
  src/test/regress/expected/upgrade_list_citus_objects.out
  src/test/regress/expected/upgrade_list_citus_objects_0.out
  src/test/regress/sql/multi_partitioning.sql
Labels: usability

#4421 Expand support for subqueries in target list through recursive planning
  src/backend/distributed/planner/recursive_planning.c
  src/test/regress/expected/subquery_in_targetlist.out
  src/test/regress/sql/subquery_in_targetlist.sql
Labels: sql

#4557 Don't use 'cstore' in symbols
  src/backend/columnar/cstore.c
  src/backend/columnar/cstore_customscan.c
  src/backend/columnar/cstore_metadata_tables.c
  src/backend/columnar/cstore_reader.c
  src/backend/columnar/cstore_tableam.c
  src/backend/columnar/cstore_writer.c
  src/backend/columnar/mod.c
  src/backend/columnar/write_state_management.c
  src/backend/distributed/operations/node_protocol.c
  src/include/columnar/cstore.h
  src/include/columnar/cstore_customscan.h
  src/include/columnar/cstore_tableam.h
Labels: columnar

#4552 More meaningful columnar metadata table names
  src/backend/columnar/cstore_metadata_tables.c
  src/backend/columnar/sql/columnar--9.5-1--10.0-1.sql
  src/backend/columnar/sql/downgrades/columnar--10.0-1--9.5-1.sql
  src/test/regress/expected/am_drop.out
  src/test/regress/expected/am_matview.out
  src/test/regress/expected/am_recursive.out
  src/test/regress/expected/am_rollback.out
  src/test/regress/expected/am_truncate.out
  src/test/regress/expected/am_vacuum.out
  src/test/regress/expected/multi_extension.out
  src/test/regress/expected/multi_extension_0.out
  src/test/regress/expected/upgrade_list_citus_objects.out
  src/test/regress/expected/upgrade_list_citus_objects_0.out
  src/test/regress/sql/am_drop.sql
  src/test/regress/sql/am_matview.sql
  src/test/regress/sql/am_recursive.sql
  src/test/regress/sql/am_rollback.sql
  src/test/regress/sql/am_truncate.sql
  src/test/regress/sql/am_vacuum.sql
Labels: columnar

#4559 Choose the smallest colocation id among all matches
  src/backend/distributed/utils/colocation_utils.c
Labels: bug

#4551 Mitigate segfault in connection statemachine
  src/backend/distributed/executor/adaptive_executor.c
Labels: backport

#4565 Read chunk row count from catalog tables
  src/backend/columnar/cstore_reader.c
  src/include/columnar/columnar.h
  src/test/regress/input/am_chunk_filtering.source
  src/test/regress/output/am_chunk_filtering.source
Labels: columnar

#4588 When reaches to pool size, COPY sets the placement access
  src/backend/distributed/commands/multi_copy.c
  src/test/regress/expected/single_node.out
  src/test/regress/sql/single_node.sql
Labels: backport

#4596 Fix a flaky behaviour in shared_connection_stats
  src/test/regress/expected/shared_connection_stats.out
  src/test/regress/sql/shared_connection_stats.sql
Labels: regression tests

#4591 Fix partition column index issue
  src/backend/distributed/planner/multi_physical_planner.c
  src/backend/distributed/sql/citus--9.5-1--10.0-1.sql
  src/backend/distributed/utils/query_utils.c
  src/backend/distributed/worker/worker_partition_protocol.c
  src/include/distributed/query_utils.h
  src/test/regress/expected/adaptive_executor_repartition.out
  src/test/regress/sql/adaptive_executor_repartition.sql
Labels: backport, bug
