Repository citusdata/citus, pull requests merged in 2022-07, with the labels that each got.

#6086 Reduce memory consumption of index name fix for partitioned tables
  src/backend/distributed/utils/listutils.c
  src/backend/distributed/utils/multi_partitioning_utils.c
  src/include/distributed/listutils.h
Labels: backport, cherry-pick-11.0

#6066 Use colocation locks in lower level UDFs and create_distributed_table
  src/backend/distributed/commands/create_distributed_table.c
  src/backend/distributed/operations/repair_shards.c
  src/backend/distributed/operations/shard_rebalancer.c
  src/backend/distributed/operations/shard_split.c
  src/include/distributed/resource_lock.h
  src/include/distributed/shard_rebalancer.h
  src/test/regress/expected/isolation_blocking_shard_split.out
  src/test/regress/expected/isolation_concurrent_move_create_table.out
  src/test/regress/expected/isolation_copy_placement_vs_copy_placement.out
  src/test/regress/expected/isolation_logical_replication_single_shard_commands.out
  src/test/regress/expected/isolation_max_client_connections.out
  src/test/regress/expected/isolation_move_placement_vs_move_placement.out
  src/test/regress/isolation_schedule
  src/test/regress/spec/isolation_blocking_shard_split.spec
  src/test/regress/spec/isolation_concurrent_move_create_table.spec
  src/test/regress/spec/isolation_max_client_connections.spec
Labels: backport, cherry-pick-11.0

#6090 Avoid possible information leakage about existing users
  src/backend/distributed/shared_library_init.c
Labels: backport, cherry-pick-11.0

#6030 Bugfix for IN clause to be considered during planner phase in Columnar
  src/backend/columnar/columnar_customscan.c
  src/test/regress/expected/columnar_chunk_filtering.out
  src/test/regress/sql/columnar_chunk_filtering.sql
Labels: columnar

#6059 Fix casts in insert into local table select from distributed
  src/backend/distributed/executor/insert_select_executor.c
  src/backend/distributed/planner/insert_select_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/include/distributed/insert_select_executor.h
  src/test/regress/expected/coordinator_shouldhaveshards.out
  src/test/regress/expected/insert_select_into_local_table.out
  src/test/regress/expected/insert_select_repartition.out
  src/test/regress/expected/multi_explain.out
  src/test/regress/expected/multi_insert_select.out
  src/test/regress/expected/mx_coordinator_shouldhaveshards.out
  src/test/regress/sql/insert_select_into_local_table.sql
  src/test/regress/sql/multi_insert_select.sql
Labels: backport, cherry-pick-10.2, cherry-pick-11.0

#6101 Removed USE_PGXS snippet in Columnar Makefile
  src/backend/columnar/Makefile
Labels: columnar

#6105 Fixes a crash that can happen due to catalog read in shmem_exit
  src/backend/distributed/connection/shared_connection_stats.c
Labels: backport, cherry-pick-11.0
