Repository citusdata/citus, pull requests merged in 2022-06, with the labels that each got.

#5982 Fix materialized view intermediate result filename
  src/backend/distributed/executor/intermediate_results.c
  src/backend/distributed/transaction/transaction_management.c
  src/include/distributed/intermediate_results.h
  src/test/regress/expected/intermediate_results.out
  src/test/regress/sql/intermediate_results.sql
Labels: backport

#6006 Fix creating stats bug when CREATE TABLE LIKE
  src/backend/distributed/deparser/qualify_statistics_stmt.c
  src/test/regress/expected/pg14.out
  src/test/regress/sql/pg14.sql
Labels: cherry-pick-11.0

#6026 Fixes a bug that prevents using COMPRESSION and CONSTRAINT on a column
  src/backend/distributed/deparser/citus_ruleutils.c
  src/test/regress/expected/pg14.out
  src/test/regress/sql/pg14.sql
Labels: backport, cherry-pick-11.0
