Repository citusdata/citus, pull requests merged in 2022-10, with the labels that each got.

#6337 [Columnar] Bugfix for Columnar: options ignored during ALTER TABLE rewrite
  src/backend/columnar/columnar_tableam.c
  src/backend/columnar/write_state_management.c
  src/include/columnar/columnar.h
  src/test/regress/expected/columnar_alter_set_type.out
  src/test/regress/sql/columnar_alter_set_type.sql
Labels: columnar

#6387 Use original relation to retrieve column name because of syscache
  src/backend/distributed/commands/alter_table.c
  src/test/regress/expected/alter_distributed_table.out
  src/test/regress/sql/alter_distributed_table.sql
Labels: backport, cherry-pick-11.0, cherry-pick-11.1

#6398 Retain trigger settings when re-creating the triggers (on shards)
  src/backend/distributed/commands/trigger.c
  src/test/regress/expected/citus_local_table_triggers.out
  src/test/regress/expected/citus_table_triggers.out
  src/test/regress/expected/distributed_triggers.out
  src/test/regress/sql/citus_local_table_triggers.sql
  src/test/regress/sql/distributed_triggers.sql
Labels: cherry-pick-11.0, cherry-pick-11.1

#6411 [Columnar] Bugfix for Columnar: options ignored during ALTER TABLE
  src/backend/columnar/columnar_tableam.c
  src/backend/columnar/write_state_management.c
  src/include/columnar/columnar.h
  src/test/regress/expected/columnar_alter_set_type.out
  src/test/regress/sql/columnar_alter_set_type.sql
Labels: columnar, cherry-pick-11.1

#6410 [Columnar] 11.0 Cherry-Pick Bugfix for Columnar: options ignored during ALTER TABLE
  src/backend/columnar/columnar_tableam.c
  src/backend/columnar/write_state_management.c
  src/include/columnar/columnar.h
  src/test/regress/expected/columnar_alter_set_type.out
  src/test/regress/sql/columnar_alter_set_type.sql
Labels: columnar, cherry-pick-11.0

#6419 Use memcpy instead of memcpy_s to avoid pointless limits in columnar
  src/backend/columnar/columnar_metadata.c
  src/backend/columnar/columnar_tableam.c
  src/backend/columnar/columnar_writer.c
Labels: columnar, cherry-pick-10.2, cherry-pick-11.0, cherry-pick-11.1

#6417 Fixes empty password issue
  src/backend/distributed/commands/role.c
  src/test/regress/expected/alter_role_propagation.out
  src/test/regress/sql/alter_role_propagation.sql
Labels: cherry-pick-11.0, cherry-pick-11.1

#6425 Hint users to call "citus_set_coordinator_host" first
  src/backend/distributed/operations/worker_node_manager.c
  src/test/regress/expected/citus_local_tables.out
  src/test/regress/expected/isolation_create_citus_local_table.out
  src/test/regress/sql/citus_local_tables.sql
Labels: backport, cherry-pick-11.1

#6428 Properly set col names for shard rels that citus_extradata_container points to
  src/backend/distributed/deparser/ruleutils_13.c
  src/backend/distributed/deparser/ruleutils_14.c
  src/backend/distributed/deparser/ruleutils_15.c
  src/test/regress/expected/multi_view.out
  src/test/regress/sql/multi_view.sql
Labels: backport

#6441 Drop worker_fetch_foreign_file/worker_repartition_cleanup only if they exist when upgrading Citus
  src/backend/distributed/sql/citus--11.0-4--11.1-1.sql
Labels: backport, cherry-pick-11.1
