Repository citusdata/citus, pull requests merged in 2022-04, with the labels that each got.

#5805 Separate build of citus.so and citus_columnar.so.
  Makefile
  src/backend/columnar/Makefile
  src/backend/columnar/columnar.c
  src/backend/columnar/columnar_debug.c
  src/backend/columnar/columnar_tableam.c
  src/backend/columnar/mod.c
  src/backend/columnar/safeclib
  src/backend/distributed/Makefile
  src/backend/distributed/commands/alter_table.c
  src/backend/distributed/operations/node_protocol.c
  src/backend/distributed/shared_library_init.c
  src/include/columnar/columnar.h
  src/include/columnar/mod.h
  src/include/distributed/shared_library_init.h
  src/test/regress/expected/columnar_create.out
  src/test/regress/sql/columnar_create.sql
Labels: columnar

#5883 Handle user-defined type parameters in EXPLAIN ANALYZE
  src/backend/distributed/planner/multi_explain.c
  src/test/regress/expected/multi_explain.out
  src/test/regress/sql/multi_explain.sql
Labels: bug, backport

#5882 Fix EXPLAIN ANALYZE JSON format for subplans
  src/backend/distributed/planner/multi_explain.c
  src/test/regress/expected/multi_explain.out
  src/test/regress/sql/multi_explain.sql
Labels: bug, backport

#5879 Allow adding a unique constraint with an index
  src/backend/distributed/relay/relay_event_utility.c
  src/test/regress/expected/multi_alter_table_add_constraints.out
  src/test/regress/sql/multi_alter_table_add_constraints.sql
Labels: bug

#5901 Do not assign distributed transaction ids for local execution
  src/backend/distributed/executor/local_executor.c
  src/backend/distributed/transaction/transaction_management.c
  src/test/regress/expected/local_shard_execution.out
  src/test/regress/expected/single_node.out
  src/test/regress/multi_mx_schedule
  src/test/regress/sql/local_shard_execution.sql
  src/test/regress/sql/single_node.sql
Labels: cherry-pick-11.0

#5906 Do not set coordinator's metadatasynced column to false
  src/backend/distributed/metadata/node_metadata.c
  src/test/regress/expected/multi_remove_node_reference_table.out
  src/test/regress/sql/multi_remove_node_reference_table.sql
Labels: cherry-pick-11.0
