Repository citusdata/citus, pull requests merged in 2022-09, with the labels that each got.

#6262 Use RelationGetPrimaryKeyIndex for citus catalog tables
  src/backend/distributed/metadata/node_metadata.c
  src/backend/distributed/utils/colocation_utils.c
Labels: backport

#6290 Prohibit renaming child trigger on distributed partition pre PG15
  src/backend/distributed/commands/distribute_object_ops.c
  src/backend/distributed/commands/trigger.c
  src/include/distributed/commands.h
  src/test/regress/expected/upgrade_distributed_triggers_before.out
  src/test/regress/sql/upgrade_distributed_triggers_before.sql
Labels: backport

#6343 Fix bugs in CheckIfRelationWithSameNameExists
  src/backend/distributed/operations/shard_split.c
Labels: cherry-pick-11.1

#6328 Introduce code changes to fix Issue:6303
  src/backend/distributed/shardsplit/shardsplit_decoder.c
  src/test/regress/enterprise_isolation_logicalrep_1_schedule
  src/test/regress/expected/isolation_create_distributed_concurrently_after_drop_column.out
  src/test/regress/spec/isolation_create_distributed_concurrently_after_drop_column.spec
Labels: cherry-pick-11.1

#6345 Fix escaping in sequence dependency queries
  src/backend/distributed/commands/alter_table.c
Labels: bug, cherry-pick-11.1

#6341 ensure we have more active nodes than replication factor.
  src/backend/distributed/commands/create_distributed_table.c
  src/test/regress/expected/create_distributed_table_concurrently.out
  src/test/regress/sql/create_distributed_table_concurrently.sql
Labels: cherry-pick-11.1

#6344 Prevent failures on partitioned distributed tables with statistics objects on PG 15
  src/backend/distributed/planner/distributed_planner.c
  src/backend/distributed/planner/multi_router_planner.c
  src/backend/distributed/planner/relation_restriction_equivalence.c
  src/include/distributed/distributed_planner.h
  src/test/regress/expected/multi_fix_partition_shard_index_names.out
  src/test/regress/expected/multi_partitioning.out
  src/test/regress/sql/multi_partitioning.sql
Labels: cherry-pick-11.1

#6353 Allow create_distributed_table_concurrently on an empty node
  src/backend/distributed/commands/citus_add_local_table_to_metadata.c
  src/backend/distributed/commands/create_distributed_table.c
  src/test/regress/expected/multi_extension.out
  src/test/regress/sql/multi_extension.sql
Labels: bug, cherry-pick-11.1

#6336 Shard Split : Add / Update logging
  src/backend/distributed/operations/shard_cleaner.c
  src/backend/distributed/operations/shard_split.c
  src/backend/distributed/operations/worker_split_copy_udf.c
  src/include/distributed/shard_cleaner.h
  src/test/regress/expected/isolation_rebalancer_deferred_drop.out
  src/test/regress/expected/multi_colocated_shard_rebalance.out
  src/test/regress/expected/multi_tenant_isolation.out
  src/test/regress/expected/multi_tenant_isolation_nonblocking.out
Labels: cherry-pick-11.1

#6323 Not drop default col exprs from shard when adding local table to metadata
  src/backend/distributed/commands/citus_add_local_table_to_metadata.c
  src/backend/distributed/commands/sequence.c
  src/include/distributed/commands/sequence.h
  src/test/regress/expected/pg15.out
  src/test/regress/sql/pg15.sql
Labels: cherry-pick-10.2, cherry-pick-11.0, cherry-pick-11.1

#6340 Not allow ON DELETE/UPDATE SET DEFAULT actions on columns that default to sequences
  src/backend/distributed/commands/foreign_constraint.c
  src/test/regress/expected/multi_foreign_key.out
  src/test/regress/expected/pg15.out
  src/test/regress/expected/ref_citus_local_fkeys.out
  src/test/regress/sql/multi_foreign_key.sql
  src/test/regress/sql/pg15.sql
  src/test/regress/sql/ref_citus_local_fkeys.sql
Labels: cherry-pick-11.0, cherry-pick-11.1

#6367 Revert replica identity creation order for shard moves
  src/backend/distributed/operations/shard_split.c
  src/backend/distributed/replication/multi_logical_replication.c
Labels: backport, cherry-pick-11.1

#6314 Reuse connections for Splits and Logical Replication
  src/backend/distributed/connection/connection_management.c
  src/backend/distributed/operations/shard_cleaner.c
  src/backend/distributed/operations/shard_split.c
  src/backend/distributed/replication/multi_logical_replication.c
  src/backend/distributed/transaction/remote_transaction.c
  src/backend/distributed/transaction/worker_transaction.c
  src/include/distributed/connection_management.h
  src/include/distributed/multi_logical_replication.h
  src/include/distributed/remote_transaction.h
  src/include/distributed/worker_transaction.h
  src/test/regress/expected/failure_on_create_subscription.out
  src/test/regress/sql/failure_on_create_subscription.sql
Labels: cherry-pick-11.1
