Repository citusdata/citus, pull requests merged in 2022-08, with the labels that each got.

#6146 Fix segfault in citus_copy_shard_placement
  src/backend/distributed/operations/repair_shards.c
  src/test/regress/expected/multi_replicate_reference_table.out
  src/test/regress/sql/multi_replicate_reference_table.sql
Labels: backport, cherry-pick-11.0

#6165 Updated columnar_chunk_filter test for PG15
  src/test/regress/expected/columnar_chunk_filtering.out
  src/test/regress/sql/columnar_chunk_filtering.sql
Labels: columnar

#6170 Fix HTAB memory leaks
  src/backend/distributed/commands/alter_table.c
  src/backend/distributed/metadata/dependency.c
  src/backend/distributed/operations/shard_rebalancer.c
Labels: bug, backport, cherry-pick-11.0

#6173 Fix reference table lock contention
  src/backend/distributed/commands/create_distributed_table.c
  src/backend/distributed/commands/table.c
  src/backend/distributed/operations/create_shards.c
  src/backend/distributed/utils/reference_table_utils.c
  src/include/distributed/reference_table_utils.h
  src/test/regress/expected/isolation_reference_table.out
  src/test/regress/isolation_schedule
  src/test/regress/spec/isolation_reference_table.spec
Labels: cherry-pick-10.2, cherry-pick-11.0

#6178 [Columnar] Check for existence of Citus before creating Citus_Columnar
  src/backend/distributed/commands/extension.c
  src/test/regress/expected/multi_extension.out
  src/test/regress/sql/multi_extension.sql
Labels: columnar

#6166 Support Sequences owned by columns that are added before distributing tables
  src/backend/distributed/commands/create_distributed_table.c
  src/backend/distributed/commands/sequence.c
  src/backend/distributed/commands/table.c
  src/backend/distributed/metadata/dependency.c
  src/backend/distributed/metadata/metadata_sync.c
  src/include/distributed/metadata_sync.h
  src/test/regress/expected/sequencenes_owned_by.out
  src/test/regress/expected/upgrade_post_11_before.out
  src/test/regress/multi_1_schedule
  src/test/regress/sql/sequencenes_owned_by.sql
  src/test/regress/sql/upgrade_post_11_before.sql
Labels: cherry-pick-10.2, cherry-pick-11.0

#6175 Do not propagate GRANT ON SCHEMA from CREATE EXTENSION
  src/backend/distributed/commands/schema.c
Labels: backport, cherry-pick-11.0

#6038 Fix compilation warning on PG13 + OpenSSL 3.0
  src/backend/distributed/utils/enable_ssl.c
Labels: backport, cherry-pick-10.2, cherry-pick-11.0

#6225 Use the same colocation group for child and parent rels when altering a distributed table
  src/backend/distributed/commands/alter_table.c
  src/test/regress/expected/alter_distributed_table.out
  src/test/regress/sql/alter_distributed_table.sql
Labels: backport

#6237 Add an allow_unsafe_constraints flag for constraints without distribution column
  src/backend/distributed/commands/index.c
  src/backend/distributed/commands/table.c
  src/backend/distributed/shared_library_init.c
  src/include/distributed/commands.h
  src/test/regress/expected/multi_alter_table_add_constraints.out
  src/test/regress/expected/multi_create_table_constraints.out
  src/test/regress/expected/multi_fix_partition_shard_index_names.out
  src/test/regress/multi_1_schedule
  src/test/regress/sql/multi_alter_table_add_constraints.sql
  src/test/regress/sql/multi_create_table_constraints.sql
Labels: cherry-pick-11.0
