Repository citusdata/citus, pull requests merged in 2022-03, with the labels that each got.

#5661 Build Columnar.so and make Citus depends on it
  Makefile
  src/backend/columnar/Makefile
  src/backend/columnar/columnar_debug.c
  src/backend/columnar/mod.c
  src/backend/columnar/safeclib
  src/backend/distributed/Makefile
  src/backend/distributed/shared_library_init.c
  src/include/columnar/mod.h
Labels: columnar

#5793 Only change the sequence types if the target column type is a supported sequence type
  src/backend/distributed/commands/create_distributed_table.c
  src/include/distributed/metadata_utility.h
  src/test/regress/expected/sequences_with_different_types.out
  src/test/regress/multi_schedule
  src/test/regress/sql/sequences_with_different_types.sql
Labels: backport, cherry-pick-10.2

#5816 Fix worker node version check in the Citus 11 upgrade function
  src/backend/distributed/sql/udfs/citus_finalize_upgrade_to_citus11/11.0-1.sql
  src/backend/distributed/sql/udfs/citus_finalize_upgrade_to_citus11/latest.sql
Labels: bug
