Repository citusdata/citus, pull requests merged in 2022-05, with the labels that each got.

#5925 Refrain reading the metadata cache for all tables during upgrade
  src/backend/distributed/commands/extension.c
Labels: cherry-pick-11.0

#5940 Fixes a bug that prevents dropping/altering indexes
  src/backend/distributed/commands/index.c
  src/test/regress/expected/multi_index_statements.out
  src/test/regress/sql/multi_index_statements.sql
Labels: backport

#5962 Columnar: fix wraparound bug.
  .circleci/config.yml
  src/backend/columnar/columnar_tableam.c
  src/test/columnar_freezing/Makefile
  src/test/columnar_freezing/postgresql.conf
  src/test/columnar_freezing/t/001_columnar_freezing.pl
Labels: bug, columnar
