Repository citusdata/citus, pull requests merged in 2023-08, with the labels that each got.

#7098 PG16 compatibility - Rework PlannedStmt and Query's Permission Info
  src/backend/distributed/planner/deparse_shard_query.c
  src/backend/distributed/planner/distributed_planner.c
  src/backend/distributed/planner/fast_path_router_planner.c
  src/backend/distributed/planner/insert_select_planner.c
  src/backend/distributed/planner/local_distributed_join_planner.c
  src/backend/distributed/planner/merge_planner.c
  src/backend/distributed/planner/query_colocation_checker.c
  src/backend/distributed/planner/query_pushdown_planning.c
  src/backend/distributed/planner/recursive_planning.c
  src/backend/distributed/utils/relation_utils.c
  src/include/distributed/query_colocation_checker.h
  src/include/distributed/recursive_planning.h
  src/include/pg_version_compat.h
Labels: pg16_support

#7107 PG16 compatibility - varnullingrels additions
  src/backend/distributed/sql/udfs/citus_finish_pg_upgrade/12.1-1.sql
  src/backend/distributed/sql/udfs/citus_finish_pg_upgrade/latest.sql
  src/backend/distributed/sql/udfs/citus_prepare_pg_upgrade/12.1-1.sql
  src/backend/distributed/sql/udfs/citus_prepare_pg_upgrade/latest.sql
  src/test/regress/bin/normalize.sed
  src/test/regress/expected/citus_local_tables.out
  src/test/regress/expected/citus_local_tables_mx.out
  src/test/regress/expected/metadata_sync_helpers.out
  src/test/regress/expected/multi_extension.out
  src/test/regress/expected/multi_metadata_sync.out
  src/test/regress/expected/multi_metadata_sync_0.out
  src/test/regress/expected/multi_prune_shard_list.out
  src/test/regress/expected/single_shard_table_udfs.out
  src/test/regress/expected/start_stop_metadata_sync.out
  src/test/regress/expected/upgrade_basic_after.out
  src/test/regress/expected/upgrade_basic_before.out
  src/test/regress/sql/metadata_sync_helpers.sql
  src/test/regress/sql/multi_extension.sql
  src/test/regress/sql/upgrade_basic_after.sql
  src/test/regress/sql/upgrade_basic_before.sql
Labels: pg16_support

#7114 PG16 compatibility - new options to vacuum and analyze
  src/backend/distributed/commands/vacuum.c
  src/test/regress/expected/pg16.out
  src/test/regress/expected/pg16_0.out
  src/test/regress/multi_schedule
  src/test/regress/sql/pg16.sql
Labels: pg16_support

#7113 PG16 compatibility - fix AM dependency and grant's admin option
  src/backend/distributed/commands/role.c
  src/backend/distributed/deparser/deparse_role_stmts.c
  src/backend/distributed/metadata/dependency.c
Labels: pg16_support

#7126 PG16 compatibility - one more outer join check
  src/backend/distributed/planner/query_pushdown_planning.c
  src/backend/distributed/planner/relation_restriction_equivalence.c
  src/include/distributed/relation_restriction_equivalence.h
Labels: pg16_support

#6952 Adds PG16Beta3 support
  .circleci/config.yml
  configure
  configure.ac
  src/backend/distributed/commands/index.c
  src/include/pg_version_compat.h
  src/test/cdc/t/016_cdc_wal2json.pl
  src/test/regress/citus_tests/common.py
  src/test/regress/expected/isolation_add_remove_node.out
  src/test/regress/expected/isolation_update_node.out
  src/test/regress/spec/isolation_add_remove_node.spec
Labels: pg16_support

#7136 PG16 - Throw meaningful error for stats without a name on Citus tables
  src/backend/distributed/commands/statistics.c
  src/test/regress/expected/pg16.out
  src/test/regress/sql/pg16.sql
Labels: pg16_support

#7137 PG16 - IS JSON predicate and SYSTEM_USER tests
  src/test/regress/expected/pg16.out
  src/test/regress/sql/pg16.sql
Labels: pg16_support

#7141 PG16 - Add GENERIC_PLAN option to EXPLAIN
  src/backend/distributed/planner/multi_explain.c
  src/test/regress/expected/pg16.out
  src/test/regress/sql/pg16.sql
Labels: pg16_support

#7140 Add tests for CREATE/ALTER TABLE .. STORAGE in PG16
  src/test/regress/expected/pg16.out
  src/test/regress/sql/pg16.sql
Labels: pg16_support

#7152 PQputCopyData's return value 0 should be considered fail
  src/backend/distributed/connection/remote_commands.c
Labels: bug, backport

#7162 Disable statistics collection
  src/backend/distributed/shared_library_init.c
  src/backend/distributed/utils/statistics_collection.c
Labels: backport
