Repository citusdata/citus, pull requests merged in 2023-04, with the labels that each got.

#6805 Do not override combinefunc of custom aggregates with common names
  src/backend/distributed/planner/multi_logical_optimizer.c
  src/test/regress/expected/aggregate_support.out
  src/test/regress/sql/aggregate_support.sql
Labels: bug

#6837 fixes update propagation bug when `citus_set_coordinator_host` is called more than once
  src/backend/distributed/metadata/node_metadata.c
  src/test/regress/expected/failure_mx_metadata_sync_multi_trans.out
  src/test/regress/sql/failure_mx_metadata_sync_multi_trans.sql
Labels: backport

#6889 break sequence dependency during table creation
  src/backend/distributed/commands/alter_table.c
  src/backend/distributed/commands/dependencies.c
  src/backend/distributed/metadata/metadata_sync.c
  src/include/distributed/metadata_sync.h
  src/test/regress/expected/failure_mx_metadata_sync_multi_trans.out
  src/test/regress/expected/multi_metadata_sync.out
  src/test/regress/expected/multi_metadata_sync_0.out
  src/test/regress/sql/failure_mx_metadata_sync_multi_trans.sql
Labels: cherry-pick-11.3
