Repository citusdata/citus, pull requests merged in 2023-03, with the labels that each got.

#6748 Use pg_total_relation_size in citus_shards
  src/backend/distributed/metadata/metadata_utility.c
  src/test/regress/citus_tests/run_test.py
  src/test/regress/expected/citus_update_table_statistics.out
  src/test/regress/expected/multi_mx_create_table.out
Labels: backport

#6721 Exclude-Generated-Columns-In-Copy
  src/backend/distributed/operations/worker_copy_table_to_node_udf.c
  src/backend/distributed/operations/worker_shard_copy.c
  src/backend/distributed/operations/worker_split_copy_udf.c
  src/include/distributed/worker_shard_copy.h
  src/test/regress/expected/citus_non_blocking_split_shards.out
  src/test/regress/expected/citus_split_shard_by_split_points.out
  src/test/regress/expected/multi_move_mx.out
  src/test/regress/expected/worker_split_copy_test.out
  src/test/regress/sql/citus_non_blocking_split_shards.sql
  src/test/regress/sql/citus_split_shard_by_split_points.sql
  src/test/regress/sql/multi_move_mx.sql
  src/test/regress/sql/worker_split_copy_test.sql
Labels: cherry-pick-11.1, cherry-pick-11.2

#6802 Handle identity columns properly in the router planner
  src/backend/distributed/deparser/citus_ruleutils.c
  src/test/regress/expected/generated_identity.out
  src/test/regress/sql/generated_identity.sql
Labels: backport, cherry-pick-11.2
