Repository citusdata/citus, pull requests merged in 2024-04, with the labels that each got.

#7573 Use expecteddir option when running vanilla tests
  src/test/regress/pg_regress_multi.pl
Labels: backport, cherry-pick-12.1

#7575 Speed up EnsureSequenceTypeSupported
  src/backend/distributed/commands/create_distributed_table.c
  src/backend/distributed/metadata/metadata_sync.c
  src/include/distributed/metadata_sync.h
Labels: backport, performance, dev_reported, schema-based-sharding, cherry-pick-12.1

#7579 Speed up SequenceUsedInDistributedTable
  src/backend/distributed/commands/sequence.c
  src/backend/distributed/metadata/metadata_sync.c
  src/include/distributed/metadata_sync.h
Labels: backport, performance, dev_reported, schema-based-sharding, cherry-pick-12.1

#7578 Speed up GetForeignKeyOids
  src/backend/distributed/commands/foreign_constraint.c
Labels: backport, performance, dev_reported, schema-based-sharding, cherry-pick-12.1

#7570 Add missing volatile qualifier.
  src/backend/distributed/connection/remote_commands.c
  src/backend/distributed/utils/citus_depended_object.c
Labels: bug, backport, user_reported, cherry-pick-12.1

#7577 Greatly speed up "\d tablename" on servers with many tables
  src/backend/distributed/worker/worker_shard_visibility.c
  src/test/regress/expected/multi_mx_hide_shard_names.out
  src/test/regress/sql/multi_mx_hide_shard_names.sql
Labels: backport, performance, dev_reported, schema-based-sharding, cherry-pick-12.1
